// Code generated by "stringer -type=MaintenanceSafety -linecomment"; DO NOT EDIT.

package repository

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FullMaintenanceSafety-0]
	_ = x[NoMaintenanceSafety-1]
}

const _MaintenanceSafety_name = "FullMaintenanceSafetyNoMaintenanceSafety"

var _MaintenanceSafety_index = [...]uint8{0, 21, 40}

func (i MaintenanceSafety) String() string {
	if i < 0 || i >= MaintenanceSafety(len(_MaintenanceSafety_index)-1) {
		return "MaintenanceSafety(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MaintenanceSafety_name[_MaintenanceSafety_index[i]:_MaintenanceSafety_index[i+1]]
}
