// Code generated by "stringer -type=MaintenanceType -linecomment"; DO NOT EDIT.

package repository

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompleteMaintenance-0]
	_ = x[MetadataMaintenance-1]
}

const _MaintenanceType_name = "CompleteMaintenanceMetadataMaintenance"

var _MaintenanceType_index = [...]uint8{0, 19, 38}

func (i MaintenanceType) String() string {
	if i < 0 || i >= MaintenanceType(len(_MaintenanceType_index)-1) {
		return "MaintenanceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MaintenanceType_name[_MaintenanceType_index[i]:_MaintenanceType_index[i+1]]
}
