// Code generated by "stringer -type=Operation"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpUnknown-0]
	_ = x[Backup-1]
	_ = x[Restore-2]
}

const _Operation_name = "OpUnknownBackupRestore"

var _Operation_index = [...]uint8{0, 9, 15, 22}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
