// Code generated by "stringer -type=CollisionPolicy"; DO NOT EDIT.

package control

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Copy-1]
	_ = x[Skip-2]
	_ = x[Replace-3]
}

const _CollisionPolicy_name = "UnknownCopySkipReplace"

var _CollisionPolicy_index = [...]uint8{0, 7, 11, 15, 22}

func (i CollisionPolicy) String() string {
	if i < 0 || i >= CollisionPolicy(len(_CollisionPolicy_index)-1) {
		return "CollisionPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CollisionPolicy_name[_CollisionPolicy_index[i]:_CollisionPolicy_index[i+1]]
}
