package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AndroidDeviceOwnerGeneralDeviceConfigurationable 
type AndroidDeviceOwnerGeneralDeviceConfigurationable interface {
    DeviceConfigurationable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccountsBlockModification()(*bool)
    GetAppsAllowInstallFromUnknownSources()(*bool)
    GetAppsAutoUpdatePolicy()(*AndroidDeviceOwnerAppAutoUpdatePolicyType)
    GetAppsDefaultPermissionPolicy()(*AndroidDeviceOwnerDefaultAppPermissionPolicyType)
    GetAppsRecommendSkippingFirstUseHints()(*bool)
    GetAzureAdSharedDeviceDataClearApps()([]AppListItemable)
    GetBluetoothBlockConfiguration()(*bool)
    GetBluetoothBlockContactSharing()(*bool)
    GetCameraBlocked()(*bool)
    GetCellularBlockWiFiTethering()(*bool)
    GetCertificateCredentialConfigurationDisabled()(*bool)
    GetCrossProfilePoliciesAllowCopyPaste()(*bool)
    GetCrossProfilePoliciesAllowDataSharing()(*AndroidDeviceOwnerCrossProfileDataSharing)
    GetCrossProfilePoliciesShowWorkContactsInPersonalProfile()(*bool)
    GetDataRoamingBlocked()(*bool)
    GetDateTimeConfigurationBlocked()(*bool)
    GetDetailedHelpText()(AndroidDeviceOwnerUserFacingMessageable)
    GetDeviceOwnerLockScreenMessage()(AndroidDeviceOwnerUserFacingMessageable)
    GetEnrollmentProfile()(*AndroidDeviceOwnerEnrollmentProfileType)
    GetFactoryResetBlocked()(*bool)
    GetFactoryResetDeviceAdministratorEmails()([]string)
    GetGlobalProxy()(AndroidDeviceOwnerGlobalProxyable)
    GetGoogleAccountsBlocked()(*bool)
    GetKioskCustomizationDeviceSettingsBlocked()(*bool)
    GetKioskCustomizationPowerButtonActionsBlocked()(*bool)
    GetKioskCustomizationStatusBar()(*AndroidDeviceOwnerKioskCustomizationStatusBar)
    GetKioskCustomizationSystemErrorWarnings()(*bool)
    GetKioskCustomizationSystemNavigation()(*AndroidDeviceOwnerKioskCustomizationSystemNavigation)
    GetKioskModeAppOrderEnabled()(*bool)
    GetKioskModeAppPositions()([]AndroidDeviceOwnerKioskModeAppPositionItemable)
    GetKioskModeApps()([]AppListItemable)
    GetKioskModeAppsInFolderOrderedByName()(*bool)
    GetKioskModeBluetoothConfigurationEnabled()(*bool)
    GetKioskModeDebugMenuEasyAccessEnabled()(*bool)
    GetKioskModeExitCode()(*string)
    GetKioskModeFlashlightConfigurationEnabled()(*bool)
    GetKioskModeFolderIcon()(*AndroidDeviceOwnerKioskModeFolderIcon)
    GetKioskModeGridHeight()(*int32)
    GetKioskModeGridWidth()(*int32)
    GetKioskModeIconSize()(*AndroidDeviceOwnerKioskModeIconSize)
    GetKioskModeLockHomeScreen()(*bool)
    GetKioskModeManagedFolders()([]AndroidDeviceOwnerKioskModeManagedFolderable)
    GetKioskModeManagedHomeScreenAutoSignout()(*bool)
    GetKioskModeManagedHomeScreenInactiveSignOutDelayInSeconds()(*int32)
    GetKioskModeManagedHomeScreenInactiveSignOutNoticeInSeconds()(*int32)
    GetKioskModeManagedHomeScreenPinComplexity()(*KioskModeManagedHomeScreenPinComplexity)
    GetKioskModeManagedHomeScreenPinRequired()(*bool)
    GetKioskModeManagedHomeScreenPinRequiredToResume()(*bool)
    GetKioskModeManagedHomeScreenSignInBackground()(*string)
    GetKioskModeManagedHomeScreenSignInBrandingLogo()(*string)
    GetKioskModeManagedHomeScreenSignInEnabled()(*bool)
    GetKioskModeManagedSettingsEntryDisabled()(*bool)
    GetKioskModeMediaVolumeConfigurationEnabled()(*bool)
    GetKioskModeScreenOrientation()(*AndroidDeviceOwnerKioskModeScreenOrientation)
    GetKioskModeScreenSaverConfigurationEnabled()(*bool)
    GetKioskModeScreenSaverDetectMediaDisabled()(*bool)
    GetKioskModeScreenSaverDisplayTimeInSeconds()(*int32)
    GetKioskModeScreenSaverImageUrl()(*string)
    GetKioskModeScreenSaverStartDelayInSeconds()(*int32)
    GetKioskModeShowAppNotificationBadge()(*bool)
    GetKioskModeShowDeviceInfo()(*bool)
    GetKioskModeUseManagedHomeScreenApp()(*KioskModeType)
    GetKioskModeVirtualHomeButtonEnabled()(*bool)
    GetKioskModeVirtualHomeButtonType()(*AndroidDeviceOwnerVirtualHomeButtonType)
    GetKioskModeWallpaperUrl()(*string)
    GetKioskModeWifiAllowedSsids()([]string)
    GetKioskModeWiFiConfigurationEnabled()(*bool)
    GetMicrophoneForceMute()(*bool)
    GetMicrosoftLauncherConfigurationEnabled()(*bool)
    GetMicrosoftLauncherCustomWallpaperAllowUserModification()(*bool)
    GetMicrosoftLauncherCustomWallpaperEnabled()(*bool)
    GetMicrosoftLauncherCustomWallpaperImageUrl()(*string)
    GetMicrosoftLauncherDockPresenceAllowUserModification()(*bool)
    GetMicrosoftLauncherDockPresenceConfiguration()(*MicrosoftLauncherDockPresence)
    GetMicrosoftLauncherFeedAllowUserModification()(*bool)
    GetMicrosoftLauncherFeedEnabled()(*bool)
    GetMicrosoftLauncherSearchBarPlacementConfiguration()(*MicrosoftLauncherSearchBarPlacement)
    GetNetworkEscapeHatchAllowed()(*bool)
    GetNfcBlockOutgoingBeam()(*bool)
    GetPasswordBlockKeyguard()(*bool)
    GetPasswordBlockKeyguardFeatures()([]AndroidKeyguardFeature)
    GetPasswordExpirationDays()(*int32)
    GetPasswordMinimumLength()(*int32)
    GetPasswordMinimumLetterCharacters()(*int32)
    GetPasswordMinimumLowerCaseCharacters()(*int32)
    GetPasswordMinimumNonLetterCharacters()(*int32)
    GetPasswordMinimumNumericCharacters()(*int32)
    GetPasswordMinimumSymbolCharacters()(*int32)
    GetPasswordMinimumUpperCaseCharacters()(*int32)
    GetPasswordMinutesOfInactivityBeforeScreenTimeout()(*int32)
    GetPasswordPreviousPasswordCountToBlock()(*int32)
    GetPasswordRequiredType()(*AndroidDeviceOwnerRequiredPasswordType)
    GetPasswordRequireUnlock()(*AndroidDeviceOwnerRequiredPasswordUnlock)
    GetPasswordSignInFailureCountBeforeFactoryReset()(*int32)
    GetPersonalProfileAppsAllowInstallFromUnknownSources()(*bool)
    GetPersonalProfileCameraBlocked()(*bool)
    GetPersonalProfilePersonalApplications()([]AppListItemable)
    GetPersonalProfilePlayStoreMode()(*PersonalProfilePersonalPlayStoreMode)
    GetPersonalProfileScreenCaptureBlocked()(*bool)
    GetPlayStoreMode()(*AndroidDeviceOwnerPlayStoreMode)
    GetScreenCaptureBlocked()(*bool)
    GetSecurityCommonCriteriaModeEnabled()(*bool)
    GetSecurityDeveloperSettingsEnabled()(*bool)
    GetSecurityRequireVerifyApps()(*bool)
    GetShortHelpText()(AndroidDeviceOwnerUserFacingMessageable)
    GetStatusBarBlocked()(*bool)
    GetStayOnModes()([]AndroidDeviceOwnerBatteryPluggedMode)
    GetStorageAllowUsb()(*bool)
    GetStorageBlockExternalMedia()(*bool)
    GetStorageBlockUsbFileTransfer()(*bool)
    GetSystemUpdateFreezePeriods()([]AndroidDeviceOwnerSystemUpdateFreezePeriodable)
    GetSystemUpdateInstallType()(*AndroidDeviceOwnerSystemUpdateInstallType)
    GetSystemUpdateWindowEndMinutesAfterMidnight()(*int32)
    GetSystemUpdateWindowStartMinutesAfterMidnight()(*int32)
    GetSystemWindowsBlocked()(*bool)
    GetUsersBlockAdd()(*bool)
    GetUsersBlockRemove()(*bool)
    GetVolumeBlockAdjustment()(*bool)
    GetVpnAlwaysOnLockdownMode()(*bool)
    GetVpnAlwaysOnPackageIdentifier()(*string)
    GetWifiBlockEditConfigurations()(*bool)
    GetWifiBlockEditPolicyDefinedConfigurations()(*bool)
    GetWorkProfilePasswordExpirationDays()(*int32)
    GetWorkProfilePasswordMinimumLength()(*int32)
    GetWorkProfilePasswordMinimumLetterCharacters()(*int32)
    GetWorkProfilePasswordMinimumLowerCaseCharacters()(*int32)
    GetWorkProfilePasswordMinimumNonLetterCharacters()(*int32)
    GetWorkProfilePasswordMinimumNumericCharacters()(*int32)
    GetWorkProfilePasswordMinimumSymbolCharacters()(*int32)
    GetWorkProfilePasswordMinimumUpperCaseCharacters()(*int32)
    GetWorkProfilePasswordPreviousPasswordCountToBlock()(*int32)
    GetWorkProfilePasswordRequiredType()(*AndroidDeviceOwnerRequiredPasswordType)
    GetWorkProfilePasswordRequireUnlock()(*AndroidDeviceOwnerRequiredPasswordUnlock)
    GetWorkProfilePasswordSignInFailureCountBeforeFactoryReset()(*int32)
    SetAccountsBlockModification(value *bool)()
    SetAppsAllowInstallFromUnknownSources(value *bool)()
    SetAppsAutoUpdatePolicy(value *AndroidDeviceOwnerAppAutoUpdatePolicyType)()
    SetAppsDefaultPermissionPolicy(value *AndroidDeviceOwnerDefaultAppPermissionPolicyType)()
    SetAppsRecommendSkippingFirstUseHints(value *bool)()
    SetAzureAdSharedDeviceDataClearApps(value []AppListItemable)()
    SetBluetoothBlockConfiguration(value *bool)()
    SetBluetoothBlockContactSharing(value *bool)()
    SetCameraBlocked(value *bool)()
    SetCellularBlockWiFiTethering(value *bool)()
    SetCertificateCredentialConfigurationDisabled(value *bool)()
    SetCrossProfilePoliciesAllowCopyPaste(value *bool)()
    SetCrossProfilePoliciesAllowDataSharing(value *AndroidDeviceOwnerCrossProfileDataSharing)()
    SetCrossProfilePoliciesShowWorkContactsInPersonalProfile(value *bool)()
    SetDataRoamingBlocked(value *bool)()
    SetDateTimeConfigurationBlocked(value *bool)()
    SetDetailedHelpText(value AndroidDeviceOwnerUserFacingMessageable)()
    SetDeviceOwnerLockScreenMessage(value AndroidDeviceOwnerUserFacingMessageable)()
    SetEnrollmentProfile(value *AndroidDeviceOwnerEnrollmentProfileType)()
    SetFactoryResetBlocked(value *bool)()
    SetFactoryResetDeviceAdministratorEmails(value []string)()
    SetGlobalProxy(value AndroidDeviceOwnerGlobalProxyable)()
    SetGoogleAccountsBlocked(value *bool)()
    SetKioskCustomizationDeviceSettingsBlocked(value *bool)()
    SetKioskCustomizationPowerButtonActionsBlocked(value *bool)()
    SetKioskCustomizationStatusBar(value *AndroidDeviceOwnerKioskCustomizationStatusBar)()
    SetKioskCustomizationSystemErrorWarnings(value *bool)()
    SetKioskCustomizationSystemNavigation(value *AndroidDeviceOwnerKioskCustomizationSystemNavigation)()
    SetKioskModeAppOrderEnabled(value *bool)()
    SetKioskModeAppPositions(value []AndroidDeviceOwnerKioskModeAppPositionItemable)()
    SetKioskModeApps(value []AppListItemable)()
    SetKioskModeAppsInFolderOrderedByName(value *bool)()
    SetKioskModeBluetoothConfigurationEnabled(value *bool)()
    SetKioskModeDebugMenuEasyAccessEnabled(value *bool)()
    SetKioskModeExitCode(value *string)()
    SetKioskModeFlashlightConfigurationEnabled(value *bool)()
    SetKioskModeFolderIcon(value *AndroidDeviceOwnerKioskModeFolderIcon)()
    SetKioskModeGridHeight(value *int32)()
    SetKioskModeGridWidth(value *int32)()
    SetKioskModeIconSize(value *AndroidDeviceOwnerKioskModeIconSize)()
    SetKioskModeLockHomeScreen(value *bool)()
    SetKioskModeManagedFolders(value []AndroidDeviceOwnerKioskModeManagedFolderable)()
    SetKioskModeManagedHomeScreenAutoSignout(value *bool)()
    SetKioskModeManagedHomeScreenInactiveSignOutDelayInSeconds(value *int32)()
    SetKioskModeManagedHomeScreenInactiveSignOutNoticeInSeconds(value *int32)()
    SetKioskModeManagedHomeScreenPinComplexity(value *KioskModeManagedHomeScreenPinComplexity)()
    SetKioskModeManagedHomeScreenPinRequired(value *bool)()
    SetKioskModeManagedHomeScreenPinRequiredToResume(value *bool)()
    SetKioskModeManagedHomeScreenSignInBackground(value *string)()
    SetKioskModeManagedHomeScreenSignInBrandingLogo(value *string)()
    SetKioskModeManagedHomeScreenSignInEnabled(value *bool)()
    SetKioskModeManagedSettingsEntryDisabled(value *bool)()
    SetKioskModeMediaVolumeConfigurationEnabled(value *bool)()
    SetKioskModeScreenOrientation(value *AndroidDeviceOwnerKioskModeScreenOrientation)()
    SetKioskModeScreenSaverConfigurationEnabled(value *bool)()
    SetKioskModeScreenSaverDetectMediaDisabled(value *bool)()
    SetKioskModeScreenSaverDisplayTimeInSeconds(value *int32)()
    SetKioskModeScreenSaverImageUrl(value *string)()
    SetKioskModeScreenSaverStartDelayInSeconds(value *int32)()
    SetKioskModeShowAppNotificationBadge(value *bool)()
    SetKioskModeShowDeviceInfo(value *bool)()
    SetKioskModeUseManagedHomeScreenApp(value *KioskModeType)()
    SetKioskModeVirtualHomeButtonEnabled(value *bool)()
    SetKioskModeVirtualHomeButtonType(value *AndroidDeviceOwnerVirtualHomeButtonType)()
    SetKioskModeWallpaperUrl(value *string)()
    SetKioskModeWifiAllowedSsids(value []string)()
    SetKioskModeWiFiConfigurationEnabled(value *bool)()
    SetMicrophoneForceMute(value *bool)()
    SetMicrosoftLauncherConfigurationEnabled(value *bool)()
    SetMicrosoftLauncherCustomWallpaperAllowUserModification(value *bool)()
    SetMicrosoftLauncherCustomWallpaperEnabled(value *bool)()
    SetMicrosoftLauncherCustomWallpaperImageUrl(value *string)()
    SetMicrosoftLauncherDockPresenceAllowUserModification(value *bool)()
    SetMicrosoftLauncherDockPresenceConfiguration(value *MicrosoftLauncherDockPresence)()
    SetMicrosoftLauncherFeedAllowUserModification(value *bool)()
    SetMicrosoftLauncherFeedEnabled(value *bool)()
    SetMicrosoftLauncherSearchBarPlacementConfiguration(value *MicrosoftLauncherSearchBarPlacement)()
    SetNetworkEscapeHatchAllowed(value *bool)()
    SetNfcBlockOutgoingBeam(value *bool)()
    SetPasswordBlockKeyguard(value *bool)()
    SetPasswordBlockKeyguardFeatures(value []AndroidKeyguardFeature)()
    SetPasswordExpirationDays(value *int32)()
    SetPasswordMinimumLength(value *int32)()
    SetPasswordMinimumLetterCharacters(value *int32)()
    SetPasswordMinimumLowerCaseCharacters(value *int32)()
    SetPasswordMinimumNonLetterCharacters(value *int32)()
    SetPasswordMinimumNumericCharacters(value *int32)()
    SetPasswordMinimumSymbolCharacters(value *int32)()
    SetPasswordMinimumUpperCaseCharacters(value *int32)()
    SetPasswordMinutesOfInactivityBeforeScreenTimeout(value *int32)()
    SetPasswordPreviousPasswordCountToBlock(value *int32)()
    SetPasswordRequiredType(value *AndroidDeviceOwnerRequiredPasswordType)()
    SetPasswordRequireUnlock(value *AndroidDeviceOwnerRequiredPasswordUnlock)()
    SetPasswordSignInFailureCountBeforeFactoryReset(value *int32)()
    SetPersonalProfileAppsAllowInstallFromUnknownSources(value *bool)()
    SetPersonalProfileCameraBlocked(value *bool)()
    SetPersonalProfilePersonalApplications(value []AppListItemable)()
    SetPersonalProfilePlayStoreMode(value *PersonalProfilePersonalPlayStoreMode)()
    SetPersonalProfileScreenCaptureBlocked(value *bool)()
    SetPlayStoreMode(value *AndroidDeviceOwnerPlayStoreMode)()
    SetScreenCaptureBlocked(value *bool)()
    SetSecurityCommonCriteriaModeEnabled(value *bool)()
    SetSecurityDeveloperSettingsEnabled(value *bool)()
    SetSecurityRequireVerifyApps(value *bool)()
    SetShortHelpText(value AndroidDeviceOwnerUserFacingMessageable)()
    SetStatusBarBlocked(value *bool)()
    SetStayOnModes(value []AndroidDeviceOwnerBatteryPluggedMode)()
    SetStorageAllowUsb(value *bool)()
    SetStorageBlockExternalMedia(value *bool)()
    SetStorageBlockUsbFileTransfer(value *bool)()
    SetSystemUpdateFreezePeriods(value []AndroidDeviceOwnerSystemUpdateFreezePeriodable)()
    SetSystemUpdateInstallType(value *AndroidDeviceOwnerSystemUpdateInstallType)()
    SetSystemUpdateWindowEndMinutesAfterMidnight(value *int32)()
    SetSystemUpdateWindowStartMinutesAfterMidnight(value *int32)()
    SetSystemWindowsBlocked(value *bool)()
    SetUsersBlockAdd(value *bool)()
    SetUsersBlockRemove(value *bool)()
    SetVolumeBlockAdjustment(value *bool)()
    SetVpnAlwaysOnLockdownMode(value *bool)()
    SetVpnAlwaysOnPackageIdentifier(value *string)()
    SetWifiBlockEditConfigurations(value *bool)()
    SetWifiBlockEditPolicyDefinedConfigurations(value *bool)()
    SetWorkProfilePasswordExpirationDays(value *int32)()
    SetWorkProfilePasswordMinimumLength(value *int32)()
    SetWorkProfilePasswordMinimumLetterCharacters(value *int32)()
    SetWorkProfilePasswordMinimumLowerCaseCharacters(value *int32)()
    SetWorkProfilePasswordMinimumNonLetterCharacters(value *int32)()
    SetWorkProfilePasswordMinimumNumericCharacters(value *int32)()
    SetWorkProfilePasswordMinimumSymbolCharacters(value *int32)()
    SetWorkProfilePasswordMinimumUpperCaseCharacters(value *int32)()
    SetWorkProfilePasswordPreviousPasswordCountToBlock(value *int32)()
    SetWorkProfilePasswordRequiredType(value *AndroidDeviceOwnerRequiredPasswordType)()
    SetWorkProfilePasswordRequireUnlock(value *AndroidDeviceOwnerRequiredPasswordUnlock)()
    SetWorkProfilePasswordSignInFailureCountBeforeFactoryReset(value *int32)()
}
