package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AppleVpnConfigurationable 
type AppleVpnConfigurationable interface {
    DeviceConfigurationable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAssociatedDomains()([]string)
    GetAuthenticationMethod()(*VpnAuthenticationMethod)
    GetConnectionName()(*string)
    GetConnectionType()(*AppleVpnConnectionType)
    GetCustomData()([]KeyValueable)
    GetCustomKeyValueData()([]KeyValuePairable)
    GetDisableOnDemandUserOverride()(*bool)
    GetDisconnectOnIdle()(*bool)
    GetDisconnectOnIdleTimerInSeconds()(*int32)
    GetEnablePerApp()(*bool)
    GetEnableSplitTunneling()(*bool)
    GetExcludedDomains()([]string)
    GetIdentifier()(*string)
    GetLoginGroupOrDomain()(*string)
    GetOnDemandRules()([]VpnOnDemandRuleable)
    GetOptInToDeviceIdSharing()(*bool)
    GetProviderType()(*VpnProviderType)
    GetProxyServer()(VpnProxyServerable)
    GetRealm()(*string)
    GetRole()(*string)
    GetSafariDomains()([]string)
    GetServer()(VpnServerable)
    SetAssociatedDomains(value []string)()
    SetAuthenticationMethod(value *VpnAuthenticationMethod)()
    SetConnectionName(value *string)()
    SetConnectionType(value *AppleVpnConnectionType)()
    SetCustomData(value []KeyValueable)()
    SetCustomKeyValueData(value []KeyValuePairable)()
    SetDisableOnDemandUserOverride(value *bool)()
    SetDisconnectOnIdle(value *bool)()
    SetDisconnectOnIdleTimerInSeconds(value *int32)()
    SetEnablePerApp(value *bool)()
    SetEnableSplitTunneling(value *bool)()
    SetExcludedDomains(value []string)()
    SetIdentifier(value *string)()
    SetLoginGroupOrDomain(value *string)()
    SetOnDemandRules(value []VpnOnDemandRuleable)()
    SetOptInToDeviceIdSharing(value *bool)()
    SetProviderType(value *VpnProviderType)()
    SetProxyServer(value VpnProxyServerable)()
    SetRealm(value *string)()
    SetRole(value *string)()
    SetSafariDomains(value []string)()
    SetServer(value VpnServerable)()
}
