package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DepIOSEnrollmentProfileable 
type DepIOSEnrollmentProfileable interface {
    DepEnrollmentBaseProfileable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAppearanceScreenDisabled()(*bool)
    GetAwaitDeviceConfiguredConfirmation()(*bool)
    GetCarrierActivationUrl()(*string)
    GetCompanyPortalVppTokenId()(*string)
    GetDeviceToDeviceMigrationDisabled()(*bool)
    GetEnableSharedIPad()(*bool)
    GetEnableSingleAppEnrollmentMode()(*bool)
    GetExpressLanguageScreenDisabled()(*bool)
    GetForceTemporarySession()(*bool)
    GetHomeButtonScreenDisabled()(*bool)
    GetIMessageAndFaceTimeScreenDisabled()(*bool)
    GetITunesPairingMode()(*ITunesPairingMode)
    GetManagementCertificates()([]ManagementCertificateWithThumbprintable)
    GetOnBoardingScreenDisabled()(*bool)
    GetPassCodeDisabled()(*bool)
    GetPasscodeLockGracePeriodInSeconds()(*int32)
    GetPreferredLanguageScreenDisabled()(*bool)
    GetRestoreCompletedScreenDisabled()(*bool)
    GetRestoreFromAndroidDisabled()(*bool)
    GetSharedIPadMaximumUserCount()(*int32)
    GetSimSetupScreenDisabled()(*bool)
    GetSoftwareUpdateScreenDisabled()(*bool)
    GetTemporarySessionTimeoutInSeconds()(*int32)
    GetUpdateCompleteScreenDisabled()(*bool)
    GetUserlessSharedAadModeEnabled()(*bool)
    GetUserSessionTimeoutInSeconds()(*int32)
    GetWatchMigrationScreenDisabled()(*bool)
    GetWelcomeScreenDisabled()(*bool)
    GetZoomDisabled()(*bool)
    SetAppearanceScreenDisabled(value *bool)()
    SetAwaitDeviceConfiguredConfirmation(value *bool)()
    SetCarrierActivationUrl(value *string)()
    SetCompanyPortalVppTokenId(value *string)()
    SetDeviceToDeviceMigrationDisabled(value *bool)()
    SetEnableSharedIPad(value *bool)()
    SetEnableSingleAppEnrollmentMode(value *bool)()
    SetExpressLanguageScreenDisabled(value *bool)()
    SetForceTemporarySession(value *bool)()
    SetHomeButtonScreenDisabled(value *bool)()
    SetIMessageAndFaceTimeScreenDisabled(value *bool)()
    SetITunesPairingMode(value *ITunesPairingMode)()
    SetManagementCertificates(value []ManagementCertificateWithThumbprintable)()
    SetOnBoardingScreenDisabled(value *bool)()
    SetPassCodeDisabled(value *bool)()
    SetPasscodeLockGracePeriodInSeconds(value *int32)()
    SetPreferredLanguageScreenDisabled(value *bool)()
    SetRestoreCompletedScreenDisabled(value *bool)()
    SetRestoreFromAndroidDisabled(value *bool)()
    SetSharedIPadMaximumUserCount(value *int32)()
    SetSimSetupScreenDisabled(value *bool)()
    SetSoftwareUpdateScreenDisabled(value *bool)()
    SetTemporarySessionTimeoutInSeconds(value *int32)()
    SetUpdateCompleteScreenDisabled(value *bool)()
    SetUserlessSharedAadModeEnabled(value *bool)()
    SetUserSessionTimeoutInSeconds(value *int32)()
    SetWatchMigrationScreenDisabled(value *bool)()
    SetWelcomeScreenDisabled(value *bool)()
    SetZoomDisabled(value *bool)()
}
