package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DepEnrollmentProfileable 
type DepEnrollmentProfileable interface {
    EnrollmentProfileable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAppleIdDisabled()(*bool)
    GetApplePayDisabled()(*bool)
    GetAwaitDeviceConfiguredConfirmation()(*bool)
    GetDiagnosticsDisabled()(*bool)
    GetEnableSharedIPad()(*bool)
    GetIsDefault()(*bool)
    GetIsMandatory()(*bool)
    GetITunesPairingMode()(*ITunesPairingMode)
    GetLocationDisabled()(*bool)
    GetMacOSFileVaultDisabled()(*bool)
    GetMacOSRegistrationDisabled()(*bool)
    GetManagementCertificates()([]ManagementCertificateWithThumbprintable)
    GetPassCodeDisabled()(*bool)
    GetProfileRemovalDisabled()(*bool)
    GetRestoreBlocked()(*bool)
    GetRestoreFromAndroidDisabled()(*bool)
    GetSharedIPadMaximumUserCount()(*int32)
    GetSiriDisabled()(*bool)
    GetSupervisedModeEnabled()(*bool)
    GetSupportDepartment()(*string)
    GetSupportPhoneNumber()(*string)
    GetTermsAndConditionsDisabled()(*bool)
    GetTouchIdDisabled()(*bool)
    GetZoomDisabled()(*bool)
    SetAppleIdDisabled(value *bool)()
    SetApplePayDisabled(value *bool)()
    SetAwaitDeviceConfiguredConfirmation(value *bool)()
    SetDiagnosticsDisabled(value *bool)()
    SetEnableSharedIPad(value *bool)()
    SetIsDefault(value *bool)()
    SetIsMandatory(value *bool)()
    SetITunesPairingMode(value *ITunesPairingMode)()
    SetLocationDisabled(value *bool)()
    SetMacOSFileVaultDisabled(value *bool)()
    SetMacOSRegistrationDisabled(value *bool)()
    SetManagementCertificates(value []ManagementCertificateWithThumbprintable)()
    SetPassCodeDisabled(value *bool)()
    SetProfileRemovalDisabled(value *bool)()
    SetRestoreBlocked(value *bool)()
    SetRestoreFromAndroidDisabled(value *bool)()
    SetSharedIPadMaximumUserCount(value *int32)()
    SetSiriDisabled(value *bool)()
    SetSupervisedModeEnabled(value *bool)()
    SetSupportDepartment(value *string)()
    SetSupportPhoneNumber(value *string)()
    SetTermsAndConditionsDisabled(value *bool)()
    SetTouchIdDisabled(value *bool)()
    SetZoomDisabled(value *bool)()
}
