package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// HardwareInformationable 
type HardwareInformationable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBatteryChargeCycles()(*int32)
    GetBatteryHealthPercentage()(*int32)
    GetBatteryLevelPercentage()(*float64)
    GetBatterySerialNumber()(*string)
    GetCellularTechnology()(*string)
    GetDeviceFullQualifiedDomainName()(*string)
    GetDeviceGuardLocalSystemAuthorityCredentialGuardState()(*DeviceGuardLocalSystemAuthorityCredentialGuardState)
    GetDeviceGuardVirtualizationBasedSecurityHardwareRequirementState()(*DeviceGuardVirtualizationBasedSecurityHardwareRequirementState)
    GetDeviceGuardVirtualizationBasedSecurityState()(*DeviceGuardVirtualizationBasedSecurityState)
    GetDeviceLicensingLastErrorCode()(*int32)
    GetDeviceLicensingLastErrorDescription()(*string)
    GetDeviceLicensingStatus()(*DeviceLicensingStatus)
    GetEsimIdentifier()(*string)
    GetFreeStorageSpace()(*int64)
    GetImei()(*string)
    GetIpAddressV4()(*string)
    GetIsEncrypted()(*bool)
    GetIsSharedDevice()(*bool)
    GetIsSupervised()(*bool)
    GetManufacturer()(*string)
    GetMeid()(*string)
    GetModel()(*string)
    GetOdataType()(*string)
    GetOperatingSystemEdition()(*string)
    GetOperatingSystemLanguage()(*string)
    GetOperatingSystemProductType()(*int32)
    GetOsBuildNumber()(*string)
    GetPhoneNumber()(*string)
    GetProductName()(*string)
    GetResidentUsersCount()(*int32)
    GetSerialNumber()(*string)
    GetSharedDeviceCachedUsers()([]SharedAppleDeviceUserable)
    GetSubnetAddress()(*string)
    GetSubscriberCarrier()(*string)
    GetSystemManagementBIOSVersion()(*string)
    GetTotalStorageSpace()(*int64)
    GetTpmManufacturer()(*string)
    GetTpmSpecificationVersion()(*string)
    GetTpmVersion()(*string)
    GetWifiMac()(*string)
    GetWiredIPv4Addresses()([]string)
    SetBatteryChargeCycles(value *int32)()
    SetBatteryHealthPercentage(value *int32)()
    SetBatteryLevelPercentage(value *float64)()
    SetBatterySerialNumber(value *string)()
    SetCellularTechnology(value *string)()
    SetDeviceFullQualifiedDomainName(value *string)()
    SetDeviceGuardLocalSystemAuthorityCredentialGuardState(value *DeviceGuardLocalSystemAuthorityCredentialGuardState)()
    SetDeviceGuardVirtualizationBasedSecurityHardwareRequirementState(value *DeviceGuardVirtualizationBasedSecurityHardwareRequirementState)()
    SetDeviceGuardVirtualizationBasedSecurityState(value *DeviceGuardVirtualizationBasedSecurityState)()
    SetDeviceLicensingLastErrorCode(value *int32)()
    SetDeviceLicensingLastErrorDescription(value *string)()
    SetDeviceLicensingStatus(value *DeviceLicensingStatus)()
    SetEsimIdentifier(value *string)()
    SetFreeStorageSpace(value *int64)()
    SetImei(value *string)()
    SetIpAddressV4(value *string)()
    SetIsEncrypted(value *bool)()
    SetIsSharedDevice(value *bool)()
    SetIsSupervised(value *bool)()
    SetManufacturer(value *string)()
    SetMeid(value *string)()
    SetModel(value *string)()
    SetOdataType(value *string)()
    SetOperatingSystemEdition(value *string)()
    SetOperatingSystemLanguage(value *string)()
    SetOperatingSystemProductType(value *int32)()
    SetOsBuildNumber(value *string)()
    SetPhoneNumber(value *string)()
    SetProductName(value *string)()
    SetResidentUsersCount(value *int32)()
    SetSerialNumber(value *string)()
    SetSharedDeviceCachedUsers(value []SharedAppleDeviceUserable)()
    SetSubnetAddress(value *string)()
    SetSubscriberCarrier(value *string)()
    SetSystemManagementBIOSVersion(value *string)()
    SetTotalStorageSpace(value *int64)()
    SetTpmManufacturer(value *string)()
    SetTpmSpecificationVersion(value *string)()
    SetTpmVersion(value *string)()
    SetWifiMac(value *string)()
    SetWiredIPv4Addresses(value []string)()
}
