package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// IntuneBrandable 
type IntuneBrandable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCompanyPortalBlockedActions()([]CompanyPortalBlockedActionable)
    GetContactITEmailAddress()(*string)
    GetContactITName()(*string)
    GetContactITNotes()(*string)
    GetContactITPhoneNumber()(*string)
    GetCustomCanSeePrivacyMessage()(*string)
    GetCustomCantSeePrivacyMessage()(*string)
    GetCustomPrivacyMessage()(*string)
    GetDarkBackgroundLogo()(MimeContentable)
    GetDisableClientTelemetry()(*bool)
    GetDisplayName()(*string)
    GetEnrollmentAvailability()(*EnrollmentAvailabilityOptions)
    GetIsFactoryResetDisabled()(*bool)
    GetIsRemoveDeviceDisabled()(*bool)
    GetLandingPageCustomizedImage()(MimeContentable)
    GetLightBackgroundLogo()(MimeContentable)
    GetOdataType()(*string)
    GetOnlineSupportSiteName()(*string)
    GetOnlineSupportSiteUrl()(*string)
    GetPrivacyUrl()(*string)
    GetRoleScopeTagIds()([]string)
    GetSendDeviceOwnershipChangePushNotification()(*bool)
    GetShowAzureADEnterpriseApps()(*bool)
    GetShowConfigurationManagerApps()(*bool)
    GetShowDisplayNameNextToLogo()(*bool)
    GetShowLogo()(*bool)
    GetShowNameNextToLogo()(*bool)
    GetShowOfficeWebApps()(*bool)
    GetThemeColor()(RgbColorable)
    SetCompanyPortalBlockedActions(value []CompanyPortalBlockedActionable)()
    SetContactITEmailAddress(value *string)()
    SetContactITName(value *string)()
    SetContactITNotes(value *string)()
    SetContactITPhoneNumber(value *string)()
    SetCustomCanSeePrivacyMessage(value *string)()
    SetCustomCantSeePrivacyMessage(value *string)()
    SetCustomPrivacyMessage(value *string)()
    SetDarkBackgroundLogo(value MimeContentable)()
    SetDisableClientTelemetry(value *bool)()
    SetDisplayName(value *string)()
    SetEnrollmentAvailability(value *EnrollmentAvailabilityOptions)()
    SetIsFactoryResetDisabled(value *bool)()
    SetIsRemoveDeviceDisabled(value *bool)()
    SetLandingPageCustomizedImage(value MimeContentable)()
    SetLightBackgroundLogo(value MimeContentable)()
    SetOdataType(value *string)()
    SetOnlineSupportSiteName(value *string)()
    SetOnlineSupportSiteUrl(value *string)()
    SetPrivacyUrl(value *string)()
    SetRoleScopeTagIds(value []string)()
    SetSendDeviceOwnershipChangePushNotification(value *bool)()
    SetShowAzureADEnterpriseApps(value *bool)()
    SetShowConfigurationManagerApps(value *bool)()
    SetShowDisplayNameNextToLogo(value *bool)()
    SetShowLogo(value *bool)()
    SetShowNameNextToLogo(value *bool)()
    SetShowOfficeWebApps(value *bool)()
    SetThemeColor(value RgbColorable)()
}
