package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// IntuneBrandingProfileable 
type IntuneBrandingProfileable interface {
    Entityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAssignments()([]IntuneBrandingProfileAssignmentable)
    GetCompanyPortalBlockedActions()([]CompanyPortalBlockedActionable)
    GetContactITEmailAddress()(*string)
    GetContactITName()(*string)
    GetContactITNotes()(*string)
    GetContactITPhoneNumber()(*string)
    GetCreatedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetCustomCanSeePrivacyMessage()(*string)
    GetCustomCantSeePrivacyMessage()(*string)
    GetCustomPrivacyMessage()(*string)
    GetDisableClientTelemetry()(*bool)
    GetDisplayName()(*string)
    GetEnrollmentAvailability()(*EnrollmentAvailabilityOptions)
    GetIsDefaultProfile()(*bool)
    GetIsFactoryResetDisabled()(*bool)
    GetIsRemoveDeviceDisabled()(*bool)
    GetLandingPageCustomizedImage()(MimeContentable)
    GetLastModifiedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetLightBackgroundLogo()(MimeContentable)
    GetOnlineSupportSiteName()(*string)
    GetOnlineSupportSiteUrl()(*string)
    GetPrivacyUrl()(*string)
    GetProfileDescription()(*string)
    GetProfileName()(*string)
    GetRoleScopeTagIds()([]string)
    GetSendDeviceOwnershipChangePushNotification()(*bool)
    GetShowAzureADEnterpriseApps()(*bool)
    GetShowConfigurationManagerApps()(*bool)
    GetShowDisplayNameNextToLogo()(*bool)
    GetShowLogo()(*bool)
    GetShowOfficeWebApps()(*bool)
    GetThemeColor()(RgbColorable)
    GetThemeColorLogo()(MimeContentable)
    SetAssignments(value []IntuneBrandingProfileAssignmentable)()
    SetCompanyPortalBlockedActions(value []CompanyPortalBlockedActionable)()
    SetContactITEmailAddress(value *string)()
    SetContactITName(value *string)()
    SetContactITNotes(value *string)()
    SetContactITPhoneNumber(value *string)()
    SetCreatedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetCustomCanSeePrivacyMessage(value *string)()
    SetCustomCantSeePrivacyMessage(value *string)()
    SetCustomPrivacyMessage(value *string)()
    SetDisableClientTelemetry(value *bool)()
    SetDisplayName(value *string)()
    SetEnrollmentAvailability(value *EnrollmentAvailabilityOptions)()
    SetIsDefaultProfile(value *bool)()
    SetIsFactoryResetDisabled(value *bool)()
    SetIsRemoveDeviceDisabled(value *bool)()
    SetLandingPageCustomizedImage(value MimeContentable)()
    SetLastModifiedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetLightBackgroundLogo(value MimeContentable)()
    SetOnlineSupportSiteName(value *string)()
    SetOnlineSupportSiteUrl(value *string)()
    SetPrivacyUrl(value *string)()
    SetProfileDescription(value *string)()
    SetProfileName(value *string)()
    SetRoleScopeTagIds(value []string)()
    SetSendDeviceOwnershipChangePushNotification(value *bool)()
    SetShowAzureADEnterpriseApps(value *bool)()
    SetShowConfigurationManagerApps(value *bool)()
    SetShowDisplayNameNextToLogo(value *bool)()
    SetShowLogo(value *bool)()
    SetShowOfficeWebApps(value *bool)()
    SetThemeColor(value RgbColorable)()
    SetThemeColorLogo(value MimeContentable)()
}
