package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// IosEasEmailProfileConfigurationable 
type IosEasEmailProfileConfigurationable interface {
    EasEmailProfileConfigurationBaseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccountName()(*string)
    GetAuthenticationMethod()(*EasAuthenticationMethod)
    GetBlockMovingMessagesToOtherEmailAccounts()(*bool)
    GetBlockSendingEmailFromThirdPartyApps()(*bool)
    GetBlockSyncingRecentlyUsedEmailAddresses()(*bool)
    GetDerivedCredentialSettings()(DeviceManagementDerivedCredentialSettingsable)
    GetDurationOfEmailToSync()(*EmailSyncDuration)
    GetEasServices()(*EasServices)
    GetEasServicesUserOverrideEnabled()(*bool)
    GetEmailAddressSource()(*UserEmailSource)
    GetEncryptionCertificateType()(*EmailCertificateType)
    GetHostName()(*string)
    GetIdentityCertificate()(IosCertificateProfileBaseable)
    GetPerAppVPNProfileId()(*string)
    GetRequireSmime()(*bool)
    GetRequireSsl()(*bool)
    GetSigningCertificateType()(*EmailCertificateType)
    GetSmimeEnablePerMessageSwitch()(*bool)
    GetSmimeEncryptByDefaultEnabled()(*bool)
    GetSmimeEncryptByDefaultUserOverrideEnabled()(*bool)
    GetSmimeEncryptionCertificate()(IosCertificateProfileable)
    GetSmimeEncryptionCertificateUserOverrideEnabled()(*bool)
    GetSmimeSigningCertificate()(IosCertificateProfileable)
    GetSmimeSigningCertificateUserOverrideEnabled()(*bool)
    GetSmimeSigningEnabled()(*bool)
    GetSmimeSigningUserOverrideEnabled()(*bool)
    GetUseOAuth()(*bool)
    SetAccountName(value *string)()
    SetAuthenticationMethod(value *EasAuthenticationMethod)()
    SetBlockMovingMessagesToOtherEmailAccounts(value *bool)()
    SetBlockSendingEmailFromThirdPartyApps(value *bool)()
    SetBlockSyncingRecentlyUsedEmailAddresses(value *bool)()
    SetDerivedCredentialSettings(value DeviceManagementDerivedCredentialSettingsable)()
    SetDurationOfEmailToSync(value *EmailSyncDuration)()
    SetEasServices(value *EasServices)()
    SetEasServicesUserOverrideEnabled(value *bool)()
    SetEmailAddressSource(value *UserEmailSource)()
    SetEncryptionCertificateType(value *EmailCertificateType)()
    SetHostName(value *string)()
    SetIdentityCertificate(value IosCertificateProfileBaseable)()
    SetPerAppVPNProfileId(value *string)()
    SetRequireSmime(value *bool)()
    SetRequireSsl(value *bool)()
    SetSigningCertificateType(value *EmailCertificateType)()
    SetSmimeEnablePerMessageSwitch(value *bool)()
    SetSmimeEncryptByDefaultEnabled(value *bool)()
    SetSmimeEncryptByDefaultUserOverrideEnabled(value *bool)()
    SetSmimeEncryptionCertificate(value IosCertificateProfileable)()
    SetSmimeEncryptionCertificateUserOverrideEnabled(value *bool)()
    SetSmimeSigningCertificate(value IosCertificateProfileable)()
    SetSmimeSigningCertificateUserOverrideEnabled(value *bool)()
    SetSmimeSigningEnabled(value *bool)()
    SetSmimeSigningUserOverrideEnabled(value *bool)()
    SetUseOAuth(value *bool)()
}
