package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// MacOSDeviceFeaturesConfigurationable 
type MacOSDeviceFeaturesConfigurationable interface {
    AppleDeviceFeaturesConfigurationBaseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAdminShowHostInfo()(*bool)
    GetAppAssociatedDomains()([]MacOSAssociatedDomainsItemable)
    GetAssociatedDomains()([]KeyValuePairable)
    GetAuthorizedUsersListHidden()(*bool)
    GetAuthorizedUsersListHideAdminUsers()(*bool)
    GetAuthorizedUsersListHideLocalUsers()(*bool)
    GetAuthorizedUsersListHideMobileAccounts()(*bool)
    GetAuthorizedUsersListIncludeNetworkUsers()(*bool)
    GetAuthorizedUsersListShowOtherManagedUsers()(*bool)
    GetAutoLaunchItems()([]MacOSLaunchItemable)
    GetConsoleAccessDisabled()(*bool)
    GetContentCachingBlockDeletion()(*bool)
    GetContentCachingClientListenRanges()([]IpRangeable)
    GetContentCachingClientPolicy()(*MacOSContentCachingClientPolicy)
    GetContentCachingDataPath()(*string)
    GetContentCachingDisableConnectionSharing()(*bool)
    GetContentCachingEnabled()(*bool)
    GetContentCachingForceConnectionSharing()(*bool)
    GetContentCachingKeepAwake()(*bool)
    GetContentCachingLogClientIdentities()(*bool)
    GetContentCachingMaxSizeBytes()(*int64)
    GetContentCachingParents()([]string)
    GetContentCachingParentSelectionPolicy()(*MacOSContentCachingParentSelectionPolicy)
    GetContentCachingPeerFilterRanges()([]IpRangeable)
    GetContentCachingPeerListenRanges()([]IpRangeable)
    GetContentCachingPeerPolicy()(*MacOSContentCachingPeerPolicy)
    GetContentCachingPort()(*int32)
    GetContentCachingPublicRanges()([]IpRangeable)
    GetContentCachingShowAlerts()(*bool)
    GetContentCachingType()(*MacOSContentCachingType)
    GetLoginWindowText()(*string)
    GetLogOutDisabledWhileLoggedIn()(*bool)
    GetMacOSSingleSignOnExtension()(MacOSSingleSignOnExtensionable)
    GetPowerOffDisabledWhileLoggedIn()(*bool)
    GetRestartDisabled()(*bool)
    GetRestartDisabledWhileLoggedIn()(*bool)
    GetScreenLockDisableImmediate()(*bool)
    GetShutDownDisabled()(*bool)
    GetShutDownDisabledWhileLoggedIn()(*bool)
    GetSingleSignOnExtension()(SingleSignOnExtensionable)
    GetSingleSignOnExtensionPkinitCertificate()(MacOSCertificateProfileBaseable)
    GetSleepDisabled()(*bool)
    SetAdminShowHostInfo(value *bool)()
    SetAppAssociatedDomains(value []MacOSAssociatedDomainsItemable)()
    SetAssociatedDomains(value []KeyValuePairable)()
    SetAuthorizedUsersListHidden(value *bool)()
    SetAuthorizedUsersListHideAdminUsers(value *bool)()
    SetAuthorizedUsersListHideLocalUsers(value *bool)()
    SetAuthorizedUsersListHideMobileAccounts(value *bool)()
    SetAuthorizedUsersListIncludeNetworkUsers(value *bool)()
    SetAuthorizedUsersListShowOtherManagedUsers(value *bool)()
    SetAutoLaunchItems(value []MacOSLaunchItemable)()
    SetConsoleAccessDisabled(value *bool)()
    SetContentCachingBlockDeletion(value *bool)()
    SetContentCachingClientListenRanges(value []IpRangeable)()
    SetContentCachingClientPolicy(value *MacOSContentCachingClientPolicy)()
    SetContentCachingDataPath(value *string)()
    SetContentCachingDisableConnectionSharing(value *bool)()
    SetContentCachingEnabled(value *bool)()
    SetContentCachingForceConnectionSharing(value *bool)()
    SetContentCachingKeepAwake(value *bool)()
    SetContentCachingLogClientIdentities(value *bool)()
    SetContentCachingMaxSizeBytes(value *int64)()
    SetContentCachingParents(value []string)()
    SetContentCachingParentSelectionPolicy(value *MacOSContentCachingParentSelectionPolicy)()
    SetContentCachingPeerFilterRanges(value []IpRangeable)()
    SetContentCachingPeerListenRanges(value []IpRangeable)()
    SetContentCachingPeerPolicy(value *MacOSContentCachingPeerPolicy)()
    SetContentCachingPort(value *int32)()
    SetContentCachingPublicRanges(value []IpRangeable)()
    SetContentCachingShowAlerts(value *bool)()
    SetContentCachingType(value *MacOSContentCachingType)()
    SetLoginWindowText(value *string)()
    SetLogOutDisabledWhileLoggedIn(value *bool)()
    SetMacOSSingleSignOnExtension(value MacOSSingleSignOnExtensionable)()
    SetPowerOffDisabledWhileLoggedIn(value *bool)()
    SetRestartDisabled(value *bool)()
    SetRestartDisabledWhileLoggedIn(value *bool)()
    SetScreenLockDisableImmediate(value *bool)()
    SetShutDownDisabled(value *bool)()
    SetShutDownDisabledWhileLoggedIn(value *bool)()
    SetSingleSignOnExtension(value SingleSignOnExtensionable)()
    SetSingleSignOnExtensionPkinitCertificate(value MacOSCertificateProfileBaseable)()
    SetSleepDisabled(value *bool)()
}
