package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// MacOSGeneralDeviceConfigurationable 
type MacOSGeneralDeviceConfigurationable interface {
    DeviceConfigurationable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAddingGameCenterFriendsBlocked()(*bool)
    GetAirDropBlocked()(*bool)
    GetAppleWatchBlockAutoUnlock()(*bool)
    GetCameraBlocked()(*bool)
    GetClassroomAppBlockRemoteScreenObservation()(*bool)
    GetClassroomAppForceUnpromptedScreenObservation()(*bool)
    GetClassroomForceAutomaticallyJoinClasses()(*bool)
    GetClassroomForceRequestPermissionToLeaveClasses()(*bool)
    GetClassroomForceUnpromptedAppAndDeviceLock()(*bool)
    GetCompliantAppListType()(*AppListType)
    GetCompliantAppsList()([]AppListItemable)
    GetContentCachingBlocked()(*bool)
    GetDefinitionLookupBlocked()(*bool)
    GetEmailInDomainSuffixes()([]string)
    GetEraseContentAndSettingsBlocked()(*bool)
    GetGameCenterBlocked()(*bool)
    GetICloudBlockActivityContinuation()(*bool)
    GetICloudBlockAddressBook()(*bool)
    GetICloudBlockBookmarks()(*bool)
    GetICloudBlockCalendar()(*bool)
    GetICloudBlockDocumentSync()(*bool)
    GetICloudBlockMail()(*bool)
    GetICloudBlockNotes()(*bool)
    GetICloudBlockPhotoLibrary()(*bool)
    GetICloudBlockReminders()(*bool)
    GetICloudDesktopAndDocumentsBlocked()(*bool)
    GetICloudPrivateRelayBlocked()(*bool)
    GetITunesBlockFileSharing()(*bool)
    GetITunesBlockMusicService()(*bool)
    GetKeyboardBlockDictation()(*bool)
    GetKeychainBlockCloudSync()(*bool)
    GetMultiplayerGamingBlocked()(*bool)
    GetPasswordBlockAirDropSharing()(*bool)
    GetPasswordBlockAutoFill()(*bool)
    GetPasswordBlockFingerprintUnlock()(*bool)
    GetPasswordBlockModification()(*bool)
    GetPasswordBlockProximityRequests()(*bool)
    GetPasswordBlockSimple()(*bool)
    GetPasswordExpirationDays()(*int32)
    GetPasswordMaximumAttemptCount()(*int32)
    GetPasswordMinimumCharacterSetCount()(*int32)
    GetPasswordMinimumLength()(*int32)
    GetPasswordMinutesOfInactivityBeforeLock()(*int32)
    GetPasswordMinutesOfInactivityBeforeScreenTimeout()(*int32)
    GetPasswordMinutesUntilFailedLoginReset()(*int32)
    GetPasswordPreviousPasswordBlockCount()(*int32)
    GetPasswordRequired()(*bool)
    GetPasswordRequiredType()(*RequiredPasswordType)
    GetPrivacyAccessControls()([]MacOSPrivacyAccessControlItemable)
    GetSafariBlockAutofill()(*bool)
    GetScreenCaptureBlocked()(*bool)
    GetSoftwareUpdateMajorOSDeferredInstallDelayInDays()(*int32)
    GetSoftwareUpdateMinorOSDeferredInstallDelayInDays()(*int32)
    GetSoftwareUpdateNonOSDeferredInstallDelayInDays()(*int32)
    GetSoftwareUpdatesEnforcedDelayInDays()(*int32)
    GetSpotlightBlockInternetResults()(*bool)
    GetTouchIdTimeoutInHours()(*int32)
    GetUpdateDelayPolicy()(*MacOSSoftwareUpdateDelayPolicy)
    GetWallpaperModificationBlocked()(*bool)
    SetAddingGameCenterFriendsBlocked(value *bool)()
    SetAirDropBlocked(value *bool)()
    SetAppleWatchBlockAutoUnlock(value *bool)()
    SetCameraBlocked(value *bool)()
    SetClassroomAppBlockRemoteScreenObservation(value *bool)()
    SetClassroomAppForceUnpromptedScreenObservation(value *bool)()
    SetClassroomForceAutomaticallyJoinClasses(value *bool)()
    SetClassroomForceRequestPermissionToLeaveClasses(value *bool)()
    SetClassroomForceUnpromptedAppAndDeviceLock(value *bool)()
    SetCompliantAppListType(value *AppListType)()
    SetCompliantAppsList(value []AppListItemable)()
    SetContentCachingBlocked(value *bool)()
    SetDefinitionLookupBlocked(value *bool)()
    SetEmailInDomainSuffixes(value []string)()
    SetEraseContentAndSettingsBlocked(value *bool)()
    SetGameCenterBlocked(value *bool)()
    SetICloudBlockActivityContinuation(value *bool)()
    SetICloudBlockAddressBook(value *bool)()
    SetICloudBlockBookmarks(value *bool)()
    SetICloudBlockCalendar(value *bool)()
    SetICloudBlockDocumentSync(value *bool)()
    SetICloudBlockMail(value *bool)()
    SetICloudBlockNotes(value *bool)()
    SetICloudBlockPhotoLibrary(value *bool)()
    SetICloudBlockReminders(value *bool)()
    SetICloudDesktopAndDocumentsBlocked(value *bool)()
    SetICloudPrivateRelayBlocked(value *bool)()
    SetITunesBlockFileSharing(value *bool)()
    SetITunesBlockMusicService(value *bool)()
    SetKeyboardBlockDictation(value *bool)()
    SetKeychainBlockCloudSync(value *bool)()
    SetMultiplayerGamingBlocked(value *bool)()
    SetPasswordBlockAirDropSharing(value *bool)()
    SetPasswordBlockAutoFill(value *bool)()
    SetPasswordBlockFingerprintUnlock(value *bool)()
    SetPasswordBlockModification(value *bool)()
    SetPasswordBlockProximityRequests(value *bool)()
    SetPasswordBlockSimple(value *bool)()
    SetPasswordExpirationDays(value *int32)()
    SetPasswordMaximumAttemptCount(value *int32)()
    SetPasswordMinimumCharacterSetCount(value *int32)()
    SetPasswordMinimumLength(value *int32)()
    SetPasswordMinutesOfInactivityBeforeLock(value *int32)()
    SetPasswordMinutesOfInactivityBeforeScreenTimeout(value *int32)()
    SetPasswordMinutesUntilFailedLoginReset(value *int32)()
    SetPasswordPreviousPasswordBlockCount(value *int32)()
    SetPasswordRequired(value *bool)()
    SetPasswordRequiredType(value *RequiredPasswordType)()
    SetPrivacyAccessControls(value []MacOSPrivacyAccessControlItemable)()
    SetSafariBlockAutofill(value *bool)()
    SetScreenCaptureBlocked(value *bool)()
    SetSoftwareUpdateMajorOSDeferredInstallDelayInDays(value *int32)()
    SetSoftwareUpdateMinorOSDeferredInstallDelayInDays(value *int32)()
    SetSoftwareUpdateNonOSDeferredInstallDelayInDays(value *int32)()
    SetSoftwareUpdatesEnforcedDelayInDays(value *int32)()
    SetSpotlightBlockInternetResults(value *bool)()
    SetTouchIdTimeoutInHours(value *int32)()
    SetUpdateDelayPolicy(value *MacOSSoftwareUpdateDelayPolicy)()
    SetWallpaperModificationBlocked(value *bool)()
}
