package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// MacOSPrivacyAccessControlItemable 
type MacOSPrivacyAccessControlItemable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccessibility()(*Enablement)
    GetAddressBook()(*Enablement)
    GetAppleEventsAllowedReceivers()([]MacOSAppleEventReceiverable)
    GetBlockCamera()(*bool)
    GetBlockListenEvent()(*bool)
    GetBlockMicrophone()(*bool)
    GetBlockScreenCapture()(*bool)
    GetCalendar()(*Enablement)
    GetCodeRequirement()(*string)
    GetDisplayName()(*string)
    GetFileProviderPresence()(*Enablement)
    GetIdentifier()(*string)
    GetIdentifierType()(*MacOSProcessIdentifierType)
    GetMediaLibrary()(*Enablement)
    GetOdataType()(*string)
    GetPhotos()(*Enablement)
    GetPostEvent()(*Enablement)
    GetReminders()(*Enablement)
    GetSpeechRecognition()(*Enablement)
    GetStaticCodeValidation()(*bool)
    GetSystemPolicyAllFiles()(*Enablement)
    GetSystemPolicyDesktopFolder()(*Enablement)
    GetSystemPolicyDocumentsFolder()(*Enablement)
    GetSystemPolicyDownloadsFolder()(*Enablement)
    GetSystemPolicyNetworkVolumes()(*Enablement)
    GetSystemPolicyRemovableVolumes()(*Enablement)
    GetSystemPolicySystemAdminFiles()(*Enablement)
    SetAccessibility(value *Enablement)()
    SetAddressBook(value *Enablement)()
    SetAppleEventsAllowedReceivers(value []MacOSAppleEventReceiverable)()
    SetBlockCamera(value *bool)()
    SetBlockListenEvent(value *bool)()
    SetBlockMicrophone(value *bool)()
    SetBlockScreenCapture(value *bool)()
    SetCalendar(value *Enablement)()
    SetCodeRequirement(value *string)()
    SetDisplayName(value *string)()
    SetFileProviderPresence(value *Enablement)()
    SetIdentifier(value *string)()
    SetIdentifierType(value *MacOSProcessIdentifierType)()
    SetMediaLibrary(value *Enablement)()
    SetOdataType(value *string)()
    SetPhotos(value *Enablement)()
    SetPostEvent(value *Enablement)()
    SetReminders(value *Enablement)()
    SetSpeechRecognition(value *Enablement)()
    SetStaticCodeValidation(value *bool)()
    SetSystemPolicyAllFiles(value *Enablement)()
    SetSystemPolicyDesktopFolder(value *Enablement)()
    SetSystemPolicyDocumentsFolder(value *Enablement)()
    SetSystemPolicyDownloadsFolder(value *Enablement)()
    SetSystemPolicyNetworkVolumes(value *Enablement)()
    SetSystemPolicyRemovableVolumes(value *Enablement)()
    SetSystemPolicySystemAdminFiles(value *Enablement)()
}
