package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// MacOSEndpointProtectionConfigurationable 
type MacOSEndpointProtectionConfigurationable interface {
    DeviceConfigurationable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAdvancedThreatProtectionAutomaticSampleSubmission()(*Enablement)
    GetAdvancedThreatProtectionCloudDelivered()(*Enablement)
    GetAdvancedThreatProtectionDiagnosticDataCollection()(*Enablement)
    GetAdvancedThreatProtectionExcludedExtensions()([]string)
    GetAdvancedThreatProtectionExcludedFiles()([]string)
    GetAdvancedThreatProtectionExcludedFolders()([]string)
    GetAdvancedThreatProtectionExcludedProcesses()([]string)
    GetAdvancedThreatProtectionRealTime()(*Enablement)
    GetFileVaultAllowDeferralUntilSignOut()(*bool)
    GetFileVaultDisablePromptAtSignOut()(*bool)
    GetFileVaultEnabled()(*bool)
    GetFileVaultHidePersonalRecoveryKey()(*bool)
    GetFileVaultInstitutionalRecoveryKeyCertificate()([]byte)
    GetFileVaultInstitutionalRecoveryKeyCertificateFileName()(*string)
    GetFileVaultNumberOfTimesUserCanIgnore()(*int32)
    GetFileVaultPersonalRecoveryKeyHelpMessage()(*string)
    GetFileVaultPersonalRecoveryKeyRotationInMonths()(*int32)
    GetFileVaultSelectedRecoveryKeyTypes()(*MacOSFileVaultRecoveryKeyTypes)
    GetFirewallApplications()([]MacOSFirewallApplicationable)
    GetFirewallBlockAllIncoming()(*bool)
    GetFirewallEnabled()(*bool)
    GetFirewallEnableStealthMode()(*bool)
    GetGatekeeperAllowedAppSource()(*MacOSGatekeeperAppSources)
    GetGatekeeperBlockOverride()(*bool)
    SetAdvancedThreatProtectionAutomaticSampleSubmission(value *Enablement)()
    SetAdvancedThreatProtectionCloudDelivered(value *Enablement)()
    SetAdvancedThreatProtectionDiagnosticDataCollection(value *Enablement)()
    SetAdvancedThreatProtectionExcludedExtensions(value []string)()
    SetAdvancedThreatProtectionExcludedFiles(value []string)()
    SetAdvancedThreatProtectionExcludedFolders(value []string)()
    SetAdvancedThreatProtectionExcludedProcesses(value []string)()
    SetAdvancedThreatProtectionRealTime(value *Enablement)()
    SetFileVaultAllowDeferralUntilSignOut(value *bool)()
    SetFileVaultDisablePromptAtSignOut(value *bool)()
    SetFileVaultEnabled(value *bool)()
    SetFileVaultHidePersonalRecoveryKey(value *bool)()
    SetFileVaultInstitutionalRecoveryKeyCertificate(value []byte)()
    SetFileVaultInstitutionalRecoveryKeyCertificateFileName(value *string)()
    SetFileVaultNumberOfTimesUserCanIgnore(value *int32)()
    SetFileVaultPersonalRecoveryKeyHelpMessage(value *string)()
    SetFileVaultPersonalRecoveryKeyRotationInMonths(value *int32)()
    SetFileVaultSelectedRecoveryKeyTypes(value *MacOSFileVaultRecoveryKeyTypes)()
    SetFirewallApplications(value []MacOSFirewallApplicationable)()
    SetFirewallBlockAllIncoming(value *bool)()
    SetFirewallEnabled(value *bool)()
    SetFirewallEnableStealthMode(value *bool)()
    SetGatekeeperAllowedAppSource(value *MacOSGatekeeperAppSources)()
    SetGatekeeperBlockOverride(value *bool)()
}
