package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// SignInable 
type SignInable interface {
    Entityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAppDisplayName()(*string)
    GetAppId()(*string)
    GetAppliedConditionalAccessPolicies()([]AppliedConditionalAccessPolicyable)
    GetAppliedEventListeners()([]AppliedAuthenticationEventListenerable)
    GetAuthenticationAppDeviceDetails()(AuthenticationAppDeviceDetailsable)
    GetAuthenticationAppPolicyEvaluationDetails()([]AuthenticationAppPolicyDetailsable)
    GetAuthenticationContextClassReferences()([]AuthenticationContextable)
    GetAuthenticationDetails()([]AuthenticationDetailable)
    GetAuthenticationMethodsUsed()([]string)
    GetAuthenticationProcessingDetails()([]KeyValueable)
    GetAuthenticationProtocol()(*ProtocolType)
    GetAuthenticationRequirement()(*string)
    GetAuthenticationRequirementPolicies()([]AuthenticationRequirementPolicyable)
    GetAutonomousSystemNumber()(*int32)
    GetAzureResourceId()(*string)
    GetClientAppUsed()(*string)
    GetClientCredentialType()(*ClientCredentialType)
    GetConditionalAccessStatus()(*ConditionalAccessStatus)
    GetCorrelationId()(*string)
    GetCreatedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetCrossTenantAccessType()(*SignInAccessType)
    GetDeviceDetail()(DeviceDetailable)
    GetFederatedCredentialId()(*string)
    GetFlaggedForReview()(*bool)
    GetHomeTenantId()(*string)
    GetHomeTenantName()(*string)
    GetIncomingTokenType()(*IncomingTokenType)
    GetIpAddress()(*string)
    GetIpAddressFromResourceProvider()(*string)
    GetIsInteractive()(*bool)
    GetIsTenantRestricted()(*bool)
    GetLocation()(SignInLocationable)
    GetMfaDetail()(MfaDetailable)
    GetNetworkLocationDetails()([]NetworkLocationDetailable)
    GetOriginalRequestId()(*string)
    GetPrivateLinkDetails()(PrivateLinkDetailsable)
    GetProcessingTimeInMilliseconds()(*int32)
    GetResourceDisplayName()(*string)
    GetResourceId()(*string)
    GetResourceServicePrincipalId()(*string)
    GetResourceTenantId()(*string)
    GetRiskDetail()(*RiskDetail)
    GetRiskEventTypes_v2()([]string)
    GetRiskLevelAggregated()(*RiskLevel)
    GetRiskLevelDuringSignIn()(*RiskLevel)
    GetRiskState()(*RiskState)
    GetServicePrincipalCredentialKeyId()(*string)
    GetServicePrincipalCredentialThumbprint()(*string)
    GetServicePrincipalId()(*string)
    GetServicePrincipalName()(*string)
    GetSessionLifetimePolicies()([]SessionLifetimePolicyable)
    GetSignInEventTypes()([]string)
    GetSignInIdentifier()(*string)
    GetSignInIdentifierType()(*SignInIdentifierType)
    GetStatus()(SignInStatusable)
    GetTokenIssuerName()(*string)
    GetTokenIssuerType()(*TokenIssuerType)
    GetUniqueTokenIdentifier()(*string)
    GetUserAgent()(*string)
    GetUserDisplayName()(*string)
    GetUserId()(*string)
    GetUserPrincipalName()(*string)
    GetUserType()(*SignInUserType)
    SetAppDisplayName(value *string)()
    SetAppId(value *string)()
    SetAppliedConditionalAccessPolicies(value []AppliedConditionalAccessPolicyable)()
    SetAppliedEventListeners(value []AppliedAuthenticationEventListenerable)()
    SetAuthenticationAppDeviceDetails(value AuthenticationAppDeviceDetailsable)()
    SetAuthenticationAppPolicyEvaluationDetails(value []AuthenticationAppPolicyDetailsable)()
    SetAuthenticationContextClassReferences(value []AuthenticationContextable)()
    SetAuthenticationDetails(value []AuthenticationDetailable)()
    SetAuthenticationMethodsUsed(value []string)()
    SetAuthenticationProcessingDetails(value []KeyValueable)()
    SetAuthenticationProtocol(value *ProtocolType)()
    SetAuthenticationRequirement(value *string)()
    SetAuthenticationRequirementPolicies(value []AuthenticationRequirementPolicyable)()
    SetAutonomousSystemNumber(value *int32)()
    SetAzureResourceId(value *string)()
    SetClientAppUsed(value *string)()
    SetClientCredentialType(value *ClientCredentialType)()
    SetConditionalAccessStatus(value *ConditionalAccessStatus)()
    SetCorrelationId(value *string)()
    SetCreatedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetCrossTenantAccessType(value *SignInAccessType)()
    SetDeviceDetail(value DeviceDetailable)()
    SetFederatedCredentialId(value *string)()
    SetFlaggedForReview(value *bool)()
    SetHomeTenantId(value *string)()
    SetHomeTenantName(value *string)()
    SetIncomingTokenType(value *IncomingTokenType)()
    SetIpAddress(value *string)()
    SetIpAddressFromResourceProvider(value *string)()
    SetIsInteractive(value *bool)()
    SetIsTenantRestricted(value *bool)()
    SetLocation(value SignInLocationable)()
    SetMfaDetail(value MfaDetailable)()
    SetNetworkLocationDetails(value []NetworkLocationDetailable)()
    SetOriginalRequestId(value *string)()
    SetPrivateLinkDetails(value PrivateLinkDetailsable)()
    SetProcessingTimeInMilliseconds(value *int32)()
    SetResourceDisplayName(value *string)()
    SetResourceId(value *string)()
    SetResourceServicePrincipalId(value *string)()
    SetResourceTenantId(value *string)()
    SetRiskDetail(value *RiskDetail)()
    SetRiskEventTypes_v2(value []string)()
    SetRiskLevelAggregated(value *RiskLevel)()
    SetRiskLevelDuringSignIn(value *RiskLevel)()
    SetRiskState(value *RiskState)()
    SetServicePrincipalCredentialKeyId(value *string)()
    SetServicePrincipalCredentialThumbprint(value *string)()
    SetServicePrincipalId(value *string)()
    SetServicePrincipalName(value *string)()
    SetSessionLifetimePolicies(value []SessionLifetimePolicyable)()
    SetSignInEventTypes(value []string)()
    SetSignInIdentifier(value *string)()
    SetSignInIdentifierType(value *SignInIdentifierType)()
    SetStatus(value SignInStatusable)()
    SetTokenIssuerName(value *string)()
    SetTokenIssuerType(value *TokenIssuerType)()
    SetUniqueTokenIdentifier(value *string)()
    SetUserAgent(value *string)()
    SetUserDisplayName(value *string)()
    SetUserId(value *string)()
    SetUserPrincipalName(value *string)()
    SetUserType(value *SignInUserType)()
}
