package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// UserExperienceAnalyticsWorkFromAnywhereDeviceable 
type UserExperienceAnalyticsWorkFromAnywhereDeviceable interface {
    Entityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAutoPilotProfileAssigned()(*bool)
    GetAutoPilotRegistered()(*bool)
    GetAzureAdDeviceId()(*string)
    GetAzureAdJoinType()(*string)
    GetAzureAdRegistered()(*bool)
    GetCloudIdentityScore()(*float64)
    GetCloudManagementScore()(*float64)
    GetCloudProvisioningScore()(*float64)
    GetCompliancePolicySetToIntune()(*bool)
    GetDeviceId()(*string)
    GetDeviceName()(*string)
    GetHealthStatus()(*UserExperienceAnalyticsHealthState)
    GetIsCloudManagedGatewayEnabled()(*bool)
    GetManagedBy()(*string)
    GetManufacturer()(*string)
    GetModel()(*string)
    GetOsCheckFailed()(*bool)
    GetOsDescription()(*string)
    GetOsVersion()(*string)
    GetOtherWorkloadsSetToIntune()(*bool)
    GetOwnership()(*string)
    GetProcessor64BitCheckFailed()(*bool)
    GetProcessorCoreCountCheckFailed()(*bool)
    GetProcessorFamilyCheckFailed()(*bool)
    GetProcessorSpeedCheckFailed()(*bool)
    GetRamCheckFailed()(*bool)
    GetSecureBootCheckFailed()(*bool)
    GetSerialNumber()(*string)
    GetStorageCheckFailed()(*bool)
    GetTenantAttached()(*bool)
    GetTpmCheckFailed()(*bool)
    GetUpgradeEligibility()(*OperatingSystemUpgradeEligibility)
    GetWindowsScore()(*float64)
    GetWorkFromAnywhereScore()(*float64)
    SetAutoPilotProfileAssigned(value *bool)()
    SetAutoPilotRegistered(value *bool)()
    SetAzureAdDeviceId(value *string)()
    SetAzureAdJoinType(value *string)()
    SetAzureAdRegistered(value *bool)()
    SetCloudIdentityScore(value *float64)()
    SetCloudManagementScore(value *float64)()
    SetCloudProvisioningScore(value *float64)()
    SetCompliancePolicySetToIntune(value *bool)()
    SetDeviceId(value *string)()
    SetDeviceName(value *string)()
    SetHealthStatus(value *UserExperienceAnalyticsHealthState)()
    SetIsCloudManagedGatewayEnabled(value *bool)()
    SetManagedBy(value *string)()
    SetManufacturer(value *string)()
    SetModel(value *string)()
    SetOsCheckFailed(value *bool)()
    SetOsDescription(value *string)()
    SetOsVersion(value *string)()
    SetOtherWorkloadsSetToIntune(value *bool)()
    SetOwnership(value *string)()
    SetProcessor64BitCheckFailed(value *bool)()
    SetProcessorCoreCountCheckFailed(value *bool)()
    SetProcessorFamilyCheckFailed(value *bool)()
    SetProcessorSpeedCheckFailed(value *bool)()
    SetRamCheckFailed(value *bool)()
    SetSecureBootCheckFailed(value *bool)()
    SetSerialNumber(value *string)()
    SetStorageCheckFailed(value *bool)()
    SetTenantAttached(value *bool)()
    SetTpmCheckFailed(value *bool)()
    SetUpgradeEligibility(value *OperatingSystemUpgradeEligibility)()
    SetWindowsScore(value *float64)()
    SetWorkFromAnywhereScore(value *float64)()
}
