package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Windows10EndpointProtectionConfigurationable 
type Windows10EndpointProtectionConfigurationable interface {
    DeviceConfigurationable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetApplicationGuardAllowCameraMicrophoneRedirection()(*bool)
    GetApplicationGuardAllowFileSaveOnHost()(*bool)
    GetApplicationGuardAllowPersistence()(*bool)
    GetApplicationGuardAllowPrintToLocalPrinters()(*bool)
    GetApplicationGuardAllowPrintToNetworkPrinters()(*bool)
    GetApplicationGuardAllowPrintToPDF()(*bool)
    GetApplicationGuardAllowPrintToXPS()(*bool)
    GetApplicationGuardAllowVirtualGPU()(*bool)
    GetApplicationGuardBlockClipboardSharing()(*ApplicationGuardBlockClipboardSharingType)
    GetApplicationGuardBlockFileTransfer()(*ApplicationGuardBlockFileTransferType)
    GetApplicationGuardBlockNonEnterpriseContent()(*bool)
    GetApplicationGuardCertificateThumbprints()([]string)
    GetApplicationGuardEnabled()(*bool)
    GetApplicationGuardEnabledOptions()(*ApplicationGuardEnabledOptions)
    GetApplicationGuardForceAuditing()(*bool)
    GetAppLockerApplicationControl()(*AppLockerApplicationControlType)
    GetBitLockerAllowStandardUserEncryption()(*bool)
    GetBitLockerDisableWarningForOtherDiskEncryption()(*bool)
    GetBitLockerEnableStorageCardEncryptionOnMobile()(*bool)
    GetBitLockerEncryptDevice()(*bool)
    GetBitLockerFixedDrivePolicy()(BitLockerFixedDrivePolicyable)
    GetBitLockerRecoveryPasswordRotation()(*BitLockerRecoveryPasswordRotationType)
    GetBitLockerRemovableDrivePolicy()(BitLockerRemovableDrivePolicyable)
    GetBitLockerSystemDrivePolicy()(BitLockerSystemDrivePolicyable)
    GetDefenderAdditionalGuardedFolders()([]string)
    GetDefenderAdobeReaderLaunchChildProcess()(*DefenderProtectionType)
    GetDefenderAdvancedRansomewareProtectionType()(*DefenderProtectionType)
    GetDefenderAllowBehaviorMonitoring()(*bool)
    GetDefenderAllowCloudProtection()(*bool)
    GetDefenderAllowEndUserAccess()(*bool)
    GetDefenderAllowIntrusionPreventionSystem()(*bool)
    GetDefenderAllowOnAccessProtection()(*bool)
    GetDefenderAllowRealTimeMonitoring()(*bool)
    GetDefenderAllowScanArchiveFiles()(*bool)
    GetDefenderAllowScanDownloads()(*bool)
    GetDefenderAllowScanNetworkFiles()(*bool)
    GetDefenderAllowScanRemovableDrivesDuringFullScan()(*bool)
    GetDefenderAllowScanScriptsLoadedInInternetExplorer()(*bool)
    GetDefenderAttackSurfaceReductionExcludedPaths()([]string)
    GetDefenderBlockEndUserAccess()(*bool)
    GetDefenderBlockPersistenceThroughWmiType()(*DefenderAttackSurfaceType)
    GetDefenderCheckForSignaturesBeforeRunningScan()(*bool)
    GetDefenderCloudBlockLevel()(*DefenderCloudBlockLevelType)
    GetDefenderCloudExtendedTimeoutInSeconds()(*int32)
    GetDefenderDaysBeforeDeletingQuarantinedMalware()(*int32)
    GetDefenderDetectedMalwareActions()(DefenderDetectedMalwareActionsable)
    GetDefenderDisableBehaviorMonitoring()(*bool)
    GetDefenderDisableCatchupFullScan()(*bool)
    GetDefenderDisableCatchupQuickScan()(*bool)
    GetDefenderDisableCloudProtection()(*bool)
    GetDefenderDisableIntrusionPreventionSystem()(*bool)
    GetDefenderDisableOnAccessProtection()(*bool)
    GetDefenderDisableRealTimeMonitoring()(*bool)
    GetDefenderDisableScanArchiveFiles()(*bool)
    GetDefenderDisableScanDownloads()(*bool)
    GetDefenderDisableScanNetworkFiles()(*bool)
    GetDefenderDisableScanRemovableDrivesDuringFullScan()(*bool)
    GetDefenderDisableScanScriptsLoadedInInternetExplorer()(*bool)
    GetDefenderEmailContentExecution()(*DefenderProtectionType)
    GetDefenderEmailContentExecutionType()(*DefenderAttackSurfaceType)
    GetDefenderEnableLowCpuPriority()(*bool)
    GetDefenderEnableScanIncomingMail()(*bool)
    GetDefenderEnableScanMappedNetworkDrivesDuringFullScan()(*bool)
    GetDefenderExploitProtectionXml()([]byte)
    GetDefenderExploitProtectionXmlFileName()(*string)
    GetDefenderFileExtensionsToExclude()([]string)
    GetDefenderFilesAndFoldersToExclude()([]string)
    GetDefenderGuardedFoldersAllowedAppPaths()([]string)
    GetDefenderGuardMyFoldersType()(*FolderProtectionType)
    GetDefenderNetworkProtectionType()(*DefenderProtectionType)
    GetDefenderOfficeAppsExecutableContentCreationOrLaunch()(*DefenderProtectionType)
    GetDefenderOfficeAppsExecutableContentCreationOrLaunchType()(*DefenderAttackSurfaceType)
    GetDefenderOfficeAppsLaunchChildProcess()(*DefenderProtectionType)
    GetDefenderOfficeAppsLaunchChildProcessType()(*DefenderAttackSurfaceType)
    GetDefenderOfficeAppsOtherProcessInjection()(*DefenderProtectionType)
    GetDefenderOfficeAppsOtherProcessInjectionType()(*DefenderAttackSurfaceType)
    GetDefenderOfficeCommunicationAppsLaunchChildProcess()(*DefenderProtectionType)
    GetDefenderOfficeMacroCodeAllowWin32Imports()(*DefenderProtectionType)
    GetDefenderOfficeMacroCodeAllowWin32ImportsType()(*DefenderAttackSurfaceType)
    GetDefenderPotentiallyUnwantedAppAction()(*DefenderProtectionType)
    GetDefenderPreventCredentialStealingType()(*DefenderProtectionType)
    GetDefenderProcessCreation()(*DefenderProtectionType)
    GetDefenderProcessCreationType()(*DefenderAttackSurfaceType)
    GetDefenderProcessesToExclude()([]string)
    GetDefenderScanDirection()(*DefenderRealtimeScanDirection)
    GetDefenderScanMaxCpuPercentage()(*int32)
    GetDefenderScanType()(*DefenderScanType)
    GetDefenderScheduledQuickScanTime()(*i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.TimeOnly)
    GetDefenderScheduledScanDay()(*WeeklySchedule)
    GetDefenderScheduledScanTime()(*i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.TimeOnly)
    GetDefenderScriptDownloadedPayloadExecution()(*DefenderProtectionType)
    GetDefenderScriptDownloadedPayloadExecutionType()(*DefenderAttackSurfaceType)
    GetDefenderScriptObfuscatedMacroCode()(*DefenderProtectionType)
    GetDefenderScriptObfuscatedMacroCodeType()(*DefenderAttackSurfaceType)
    GetDefenderSecurityCenterBlockExploitProtectionOverride()(*bool)
    GetDefenderSecurityCenterDisableAccountUI()(*bool)
    GetDefenderSecurityCenterDisableAppBrowserUI()(*bool)
    GetDefenderSecurityCenterDisableClearTpmUI()(*bool)
    GetDefenderSecurityCenterDisableFamilyUI()(*bool)
    GetDefenderSecurityCenterDisableHardwareUI()(*bool)
    GetDefenderSecurityCenterDisableHealthUI()(*bool)
    GetDefenderSecurityCenterDisableNetworkUI()(*bool)
    GetDefenderSecurityCenterDisableNotificationAreaUI()(*bool)
    GetDefenderSecurityCenterDisableRansomwareUI()(*bool)
    GetDefenderSecurityCenterDisableSecureBootUI()(*bool)
    GetDefenderSecurityCenterDisableTroubleshootingUI()(*bool)
    GetDefenderSecurityCenterDisableVirusUI()(*bool)
    GetDefenderSecurityCenterDisableVulnerableTpmFirmwareUpdateUI()(*bool)
    GetDefenderSecurityCenterHelpEmail()(*string)
    GetDefenderSecurityCenterHelpPhone()(*string)
    GetDefenderSecurityCenterHelpURL()(*string)
    GetDefenderSecurityCenterITContactDisplay()(*DefenderSecurityCenterITContactDisplayType)
    GetDefenderSecurityCenterNotificationsFromApp()(*DefenderSecurityCenterNotificationsFromAppType)
    GetDefenderSecurityCenterOrganizationDisplayName()(*string)
    GetDefenderSignatureUpdateIntervalInHours()(*int32)
    GetDefenderSubmitSamplesConsentType()(*DefenderSubmitSamplesConsentType)
    GetDefenderUntrustedExecutable()(*DefenderProtectionType)
    GetDefenderUntrustedExecutableType()(*DefenderAttackSurfaceType)
    GetDefenderUntrustedUSBProcess()(*DefenderProtectionType)
    GetDefenderUntrustedUSBProcessType()(*DefenderAttackSurfaceType)
    GetDeviceGuardEnableSecureBootWithDMA()(*bool)
    GetDeviceGuardEnableVirtualizationBasedSecurity()(*bool)
    GetDeviceGuardLaunchSystemGuard()(*Enablement)
    GetDeviceGuardLocalSystemAuthorityCredentialGuardSettings()(*DeviceGuardLocalSystemAuthorityCredentialGuardType)
    GetDeviceGuardSecureBootWithDMA()(*SecureBootWithDMAType)
    GetDmaGuardDeviceEnumerationPolicy()(*DmaGuardDeviceEnumerationPolicyType)
    GetFirewallBlockStatefulFTP()(*bool)
    GetFirewallCertificateRevocationListCheckMethod()(*FirewallCertificateRevocationListCheckMethodType)
    GetFirewallIdleTimeoutForSecurityAssociationInSeconds()(*int32)
    GetFirewallIPSecExemptionsAllowDHCP()(*bool)
    GetFirewallIPSecExemptionsAllowICMP()(*bool)
    GetFirewallIPSecExemptionsAllowNeighborDiscovery()(*bool)
    GetFirewallIPSecExemptionsAllowRouterDiscovery()(*bool)
    GetFirewallIPSecExemptionsNone()(*bool)
    GetFirewallMergeKeyingModuleSettings()(*bool)
    GetFirewallPacketQueueingMethod()(*FirewallPacketQueueingMethodType)
    GetFirewallPreSharedKeyEncodingMethod()(*FirewallPreSharedKeyEncodingMethodType)
    GetFirewallProfileDomain()(WindowsFirewallNetworkProfileable)
    GetFirewallProfilePrivate()(WindowsFirewallNetworkProfileable)
    GetFirewallProfilePublic()(WindowsFirewallNetworkProfileable)
    GetFirewallRules()([]WindowsFirewallRuleable)
    GetLanManagerAuthenticationLevel()(*LanManagerAuthenticationLevel)
    GetLanManagerWorkstationDisableInsecureGuestLogons()(*bool)
    GetLocalSecurityOptionsAdministratorAccountName()(*string)
    GetLocalSecurityOptionsAdministratorElevationPromptBehavior()(*LocalSecurityOptionsAdministratorElevationPromptBehaviorType)
    GetLocalSecurityOptionsAllowAnonymousEnumerationOfSAMAccountsAndShares()(*bool)
    GetLocalSecurityOptionsAllowPKU2UAuthenticationRequests()(*bool)
    GetLocalSecurityOptionsAllowRemoteCallsToSecurityAccountsManager()(*string)
    GetLocalSecurityOptionsAllowRemoteCallsToSecurityAccountsManagerHelperBool()(*bool)
    GetLocalSecurityOptionsAllowSystemToBeShutDownWithoutHavingToLogOn()(*bool)
    GetLocalSecurityOptionsAllowUIAccessApplicationElevation()(*bool)
    GetLocalSecurityOptionsAllowUIAccessApplicationsForSecureLocations()(*bool)
    GetLocalSecurityOptionsAllowUndockWithoutHavingToLogon()(*bool)
    GetLocalSecurityOptionsBlockMicrosoftAccounts()(*bool)
    GetLocalSecurityOptionsBlockRemoteLogonWithBlankPassword()(*bool)
    GetLocalSecurityOptionsBlockRemoteOpticalDriveAccess()(*bool)
    GetLocalSecurityOptionsBlockUsersInstallingPrinterDrivers()(*bool)
    GetLocalSecurityOptionsClearVirtualMemoryPageFile()(*bool)
    GetLocalSecurityOptionsClientDigitallySignCommunicationsAlways()(*bool)
    GetLocalSecurityOptionsClientSendUnencryptedPasswordToThirdPartySMBServers()(*bool)
    GetLocalSecurityOptionsDetectApplicationInstallationsAndPromptForElevation()(*bool)
    GetLocalSecurityOptionsDisableAdministratorAccount()(*bool)
    GetLocalSecurityOptionsDisableClientDigitallySignCommunicationsIfServerAgrees()(*bool)
    GetLocalSecurityOptionsDisableGuestAccount()(*bool)
    GetLocalSecurityOptionsDisableServerDigitallySignCommunicationsAlways()(*bool)
    GetLocalSecurityOptionsDisableServerDigitallySignCommunicationsIfClientAgrees()(*bool)
    GetLocalSecurityOptionsDoNotAllowAnonymousEnumerationOfSAMAccounts()(*bool)
    GetLocalSecurityOptionsDoNotRequireCtrlAltDel()(*bool)
    GetLocalSecurityOptionsDoNotStoreLANManagerHashValueOnNextPasswordChange()(*bool)
    GetLocalSecurityOptionsFormatAndEjectOfRemovableMediaAllowedUser()(*LocalSecurityOptionsFormatAndEjectOfRemovableMediaAllowedUserType)
    GetLocalSecurityOptionsGuestAccountName()(*string)
    GetLocalSecurityOptionsHideLastSignedInUser()(*bool)
    GetLocalSecurityOptionsHideUsernameAtSignIn()(*bool)
    GetLocalSecurityOptionsInformationDisplayedOnLockScreen()(*LocalSecurityOptionsInformationDisplayedOnLockScreenType)
    GetLocalSecurityOptionsInformationShownOnLockScreen()(*LocalSecurityOptionsInformationShownOnLockScreenType)
    GetLocalSecurityOptionsLogOnMessageText()(*string)
    GetLocalSecurityOptionsLogOnMessageTitle()(*string)
    GetLocalSecurityOptionsMachineInactivityLimit()(*int32)
    GetLocalSecurityOptionsMachineInactivityLimitInMinutes()(*int32)
    GetLocalSecurityOptionsMinimumSessionSecurityForNtlmSspBasedClients()(*LocalSecurityOptionsMinimumSessionSecurity)
    GetLocalSecurityOptionsMinimumSessionSecurityForNtlmSspBasedServers()(*LocalSecurityOptionsMinimumSessionSecurity)
    GetLocalSecurityOptionsOnlyElevateSignedExecutables()(*bool)
    GetLocalSecurityOptionsRestrictAnonymousAccessToNamedPipesAndShares()(*bool)
    GetLocalSecurityOptionsSmartCardRemovalBehavior()(*LocalSecurityOptionsSmartCardRemovalBehaviorType)
    GetLocalSecurityOptionsStandardUserElevationPromptBehavior()(*LocalSecurityOptionsStandardUserElevationPromptBehaviorType)
    GetLocalSecurityOptionsSwitchToSecureDesktopWhenPromptingForElevation()(*bool)
    GetLocalSecurityOptionsUseAdminApprovalMode()(*bool)
    GetLocalSecurityOptionsUseAdminApprovalModeForAdministrators()(*bool)
    GetLocalSecurityOptionsVirtualizeFileAndRegistryWriteFailuresToPerUserLocations()(*bool)
    GetSmartScreenBlockOverrideForFiles()(*bool)
    GetSmartScreenEnableInShell()(*bool)
    GetUserRightsAccessCredentialManagerAsTrustedCaller()(DeviceManagementUserRightsSettingable)
    GetUserRightsActAsPartOfTheOperatingSystem()(DeviceManagementUserRightsSettingable)
    GetUserRightsAllowAccessFromNetwork()(DeviceManagementUserRightsSettingable)
    GetUserRightsBackupData()(DeviceManagementUserRightsSettingable)
    GetUserRightsBlockAccessFromNetwork()(DeviceManagementUserRightsSettingable)
    GetUserRightsChangeSystemTime()(DeviceManagementUserRightsSettingable)
    GetUserRightsCreateGlobalObjects()(DeviceManagementUserRightsSettingable)
    GetUserRightsCreatePageFile()(DeviceManagementUserRightsSettingable)
    GetUserRightsCreatePermanentSharedObjects()(DeviceManagementUserRightsSettingable)
    GetUserRightsCreateSymbolicLinks()(DeviceManagementUserRightsSettingable)
    GetUserRightsCreateToken()(DeviceManagementUserRightsSettingable)
    GetUserRightsDebugPrograms()(DeviceManagementUserRightsSettingable)
    GetUserRightsDelegation()(DeviceManagementUserRightsSettingable)
    GetUserRightsDenyLocalLogOn()(DeviceManagementUserRightsSettingable)
    GetUserRightsGenerateSecurityAudits()(DeviceManagementUserRightsSettingable)
    GetUserRightsImpersonateClient()(DeviceManagementUserRightsSettingable)
    GetUserRightsIncreaseSchedulingPriority()(DeviceManagementUserRightsSettingable)
    GetUserRightsLoadUnloadDrivers()(DeviceManagementUserRightsSettingable)
    GetUserRightsLocalLogOn()(DeviceManagementUserRightsSettingable)
    GetUserRightsLockMemory()(DeviceManagementUserRightsSettingable)
    GetUserRightsManageAuditingAndSecurityLogs()(DeviceManagementUserRightsSettingable)
    GetUserRightsManageVolumes()(DeviceManagementUserRightsSettingable)
    GetUserRightsModifyFirmwareEnvironment()(DeviceManagementUserRightsSettingable)
    GetUserRightsModifyObjectLabels()(DeviceManagementUserRightsSettingable)
    GetUserRightsProfileSingleProcess()(DeviceManagementUserRightsSettingable)
    GetUserRightsRemoteDesktopServicesLogOn()(DeviceManagementUserRightsSettingable)
    GetUserRightsRemoteShutdown()(DeviceManagementUserRightsSettingable)
    GetUserRightsRestoreData()(DeviceManagementUserRightsSettingable)
    GetUserRightsTakeOwnership()(DeviceManagementUserRightsSettingable)
    GetWindowsDefenderTamperProtection()(*WindowsDefenderTamperProtectionOptions)
    GetXboxServicesAccessoryManagementServiceStartupMode()(*ServiceStartType)
    GetXboxServicesEnableXboxGameSaveTask()(*bool)
    GetXboxServicesLiveAuthManagerServiceStartupMode()(*ServiceStartType)
    GetXboxServicesLiveGameSaveServiceStartupMode()(*ServiceStartType)
    GetXboxServicesLiveNetworkingServiceStartupMode()(*ServiceStartType)
    SetApplicationGuardAllowCameraMicrophoneRedirection(value *bool)()
    SetApplicationGuardAllowFileSaveOnHost(value *bool)()
    SetApplicationGuardAllowPersistence(value *bool)()
    SetApplicationGuardAllowPrintToLocalPrinters(value *bool)()
    SetApplicationGuardAllowPrintToNetworkPrinters(value *bool)()
    SetApplicationGuardAllowPrintToPDF(value *bool)()
    SetApplicationGuardAllowPrintToXPS(value *bool)()
    SetApplicationGuardAllowVirtualGPU(value *bool)()
    SetApplicationGuardBlockClipboardSharing(value *ApplicationGuardBlockClipboardSharingType)()
    SetApplicationGuardBlockFileTransfer(value *ApplicationGuardBlockFileTransferType)()
    SetApplicationGuardBlockNonEnterpriseContent(value *bool)()
    SetApplicationGuardCertificateThumbprints(value []string)()
    SetApplicationGuardEnabled(value *bool)()
    SetApplicationGuardEnabledOptions(value *ApplicationGuardEnabledOptions)()
    SetApplicationGuardForceAuditing(value *bool)()
    SetAppLockerApplicationControl(value *AppLockerApplicationControlType)()
    SetBitLockerAllowStandardUserEncryption(value *bool)()
    SetBitLockerDisableWarningForOtherDiskEncryption(value *bool)()
    SetBitLockerEnableStorageCardEncryptionOnMobile(value *bool)()
    SetBitLockerEncryptDevice(value *bool)()
    SetBitLockerFixedDrivePolicy(value BitLockerFixedDrivePolicyable)()
    SetBitLockerRecoveryPasswordRotation(value *BitLockerRecoveryPasswordRotationType)()
    SetBitLockerRemovableDrivePolicy(value BitLockerRemovableDrivePolicyable)()
    SetBitLockerSystemDrivePolicy(value BitLockerSystemDrivePolicyable)()
    SetDefenderAdditionalGuardedFolders(value []string)()
    SetDefenderAdobeReaderLaunchChildProcess(value *DefenderProtectionType)()
    SetDefenderAdvancedRansomewareProtectionType(value *DefenderProtectionType)()
    SetDefenderAllowBehaviorMonitoring(value *bool)()
    SetDefenderAllowCloudProtection(value *bool)()
    SetDefenderAllowEndUserAccess(value *bool)()
    SetDefenderAllowIntrusionPreventionSystem(value *bool)()
    SetDefenderAllowOnAccessProtection(value *bool)()
    SetDefenderAllowRealTimeMonitoring(value *bool)()
    SetDefenderAllowScanArchiveFiles(value *bool)()
    SetDefenderAllowScanDownloads(value *bool)()
    SetDefenderAllowScanNetworkFiles(value *bool)()
    SetDefenderAllowScanRemovableDrivesDuringFullScan(value *bool)()
    SetDefenderAllowScanScriptsLoadedInInternetExplorer(value *bool)()
    SetDefenderAttackSurfaceReductionExcludedPaths(value []string)()
    SetDefenderBlockEndUserAccess(value *bool)()
    SetDefenderBlockPersistenceThroughWmiType(value *DefenderAttackSurfaceType)()
    SetDefenderCheckForSignaturesBeforeRunningScan(value *bool)()
    SetDefenderCloudBlockLevel(value *DefenderCloudBlockLevelType)()
    SetDefenderCloudExtendedTimeoutInSeconds(value *int32)()
    SetDefenderDaysBeforeDeletingQuarantinedMalware(value *int32)()
    SetDefenderDetectedMalwareActions(value DefenderDetectedMalwareActionsable)()
    SetDefenderDisableBehaviorMonitoring(value *bool)()
    SetDefenderDisableCatchupFullScan(value *bool)()
    SetDefenderDisableCatchupQuickScan(value *bool)()
    SetDefenderDisableCloudProtection(value *bool)()
    SetDefenderDisableIntrusionPreventionSystem(value *bool)()
    SetDefenderDisableOnAccessProtection(value *bool)()
    SetDefenderDisableRealTimeMonitoring(value *bool)()
    SetDefenderDisableScanArchiveFiles(value *bool)()
    SetDefenderDisableScanDownloads(value *bool)()
    SetDefenderDisableScanNetworkFiles(value *bool)()
    SetDefenderDisableScanRemovableDrivesDuringFullScan(value *bool)()
    SetDefenderDisableScanScriptsLoadedInInternetExplorer(value *bool)()
    SetDefenderEmailContentExecution(value *DefenderProtectionType)()
    SetDefenderEmailContentExecutionType(value *DefenderAttackSurfaceType)()
    SetDefenderEnableLowCpuPriority(value *bool)()
    SetDefenderEnableScanIncomingMail(value *bool)()
    SetDefenderEnableScanMappedNetworkDrivesDuringFullScan(value *bool)()
    SetDefenderExploitProtectionXml(value []byte)()
    SetDefenderExploitProtectionXmlFileName(value *string)()
    SetDefenderFileExtensionsToExclude(value []string)()
    SetDefenderFilesAndFoldersToExclude(value []string)()
    SetDefenderGuardedFoldersAllowedAppPaths(value []string)()
    SetDefenderGuardMyFoldersType(value *FolderProtectionType)()
    SetDefenderNetworkProtectionType(value *DefenderProtectionType)()
    SetDefenderOfficeAppsExecutableContentCreationOrLaunch(value *DefenderProtectionType)()
    SetDefenderOfficeAppsExecutableContentCreationOrLaunchType(value *DefenderAttackSurfaceType)()
    SetDefenderOfficeAppsLaunchChildProcess(value *DefenderProtectionType)()
    SetDefenderOfficeAppsLaunchChildProcessType(value *DefenderAttackSurfaceType)()
    SetDefenderOfficeAppsOtherProcessInjection(value *DefenderProtectionType)()
    SetDefenderOfficeAppsOtherProcessInjectionType(value *DefenderAttackSurfaceType)()
    SetDefenderOfficeCommunicationAppsLaunchChildProcess(value *DefenderProtectionType)()
    SetDefenderOfficeMacroCodeAllowWin32Imports(value *DefenderProtectionType)()
    SetDefenderOfficeMacroCodeAllowWin32ImportsType(value *DefenderAttackSurfaceType)()
    SetDefenderPotentiallyUnwantedAppAction(value *DefenderProtectionType)()
    SetDefenderPreventCredentialStealingType(value *DefenderProtectionType)()
    SetDefenderProcessCreation(value *DefenderProtectionType)()
    SetDefenderProcessCreationType(value *DefenderAttackSurfaceType)()
    SetDefenderProcessesToExclude(value []string)()
    SetDefenderScanDirection(value *DefenderRealtimeScanDirection)()
    SetDefenderScanMaxCpuPercentage(value *int32)()
    SetDefenderScanType(value *DefenderScanType)()
    SetDefenderScheduledQuickScanTime(value *i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.TimeOnly)()
    SetDefenderScheduledScanDay(value *WeeklySchedule)()
    SetDefenderScheduledScanTime(value *i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.TimeOnly)()
    SetDefenderScriptDownloadedPayloadExecution(value *DefenderProtectionType)()
    SetDefenderScriptDownloadedPayloadExecutionType(value *DefenderAttackSurfaceType)()
    SetDefenderScriptObfuscatedMacroCode(value *DefenderProtectionType)()
    SetDefenderScriptObfuscatedMacroCodeType(value *DefenderAttackSurfaceType)()
    SetDefenderSecurityCenterBlockExploitProtectionOverride(value *bool)()
    SetDefenderSecurityCenterDisableAccountUI(value *bool)()
    SetDefenderSecurityCenterDisableAppBrowserUI(value *bool)()
    SetDefenderSecurityCenterDisableClearTpmUI(value *bool)()
    SetDefenderSecurityCenterDisableFamilyUI(value *bool)()
    SetDefenderSecurityCenterDisableHardwareUI(value *bool)()
    SetDefenderSecurityCenterDisableHealthUI(value *bool)()
    SetDefenderSecurityCenterDisableNetworkUI(value *bool)()
    SetDefenderSecurityCenterDisableNotificationAreaUI(value *bool)()
    SetDefenderSecurityCenterDisableRansomwareUI(value *bool)()
    SetDefenderSecurityCenterDisableSecureBootUI(value *bool)()
    SetDefenderSecurityCenterDisableTroubleshootingUI(value *bool)()
    SetDefenderSecurityCenterDisableVirusUI(value *bool)()
    SetDefenderSecurityCenterDisableVulnerableTpmFirmwareUpdateUI(value *bool)()
    SetDefenderSecurityCenterHelpEmail(value *string)()
    SetDefenderSecurityCenterHelpPhone(value *string)()
    SetDefenderSecurityCenterHelpURL(value *string)()
    SetDefenderSecurityCenterITContactDisplay(value *DefenderSecurityCenterITContactDisplayType)()
    SetDefenderSecurityCenterNotificationsFromApp(value *DefenderSecurityCenterNotificationsFromAppType)()
    SetDefenderSecurityCenterOrganizationDisplayName(value *string)()
    SetDefenderSignatureUpdateIntervalInHours(value *int32)()
    SetDefenderSubmitSamplesConsentType(value *DefenderSubmitSamplesConsentType)()
    SetDefenderUntrustedExecutable(value *DefenderProtectionType)()
    SetDefenderUntrustedExecutableType(value *DefenderAttackSurfaceType)()
    SetDefenderUntrustedUSBProcess(value *DefenderProtectionType)()
    SetDefenderUntrustedUSBProcessType(value *DefenderAttackSurfaceType)()
    SetDeviceGuardEnableSecureBootWithDMA(value *bool)()
    SetDeviceGuardEnableVirtualizationBasedSecurity(value *bool)()
    SetDeviceGuardLaunchSystemGuard(value *Enablement)()
    SetDeviceGuardLocalSystemAuthorityCredentialGuardSettings(value *DeviceGuardLocalSystemAuthorityCredentialGuardType)()
    SetDeviceGuardSecureBootWithDMA(value *SecureBootWithDMAType)()
    SetDmaGuardDeviceEnumerationPolicy(value *DmaGuardDeviceEnumerationPolicyType)()
    SetFirewallBlockStatefulFTP(value *bool)()
    SetFirewallCertificateRevocationListCheckMethod(value *FirewallCertificateRevocationListCheckMethodType)()
    SetFirewallIdleTimeoutForSecurityAssociationInSeconds(value *int32)()
    SetFirewallIPSecExemptionsAllowDHCP(value *bool)()
    SetFirewallIPSecExemptionsAllowICMP(value *bool)()
    SetFirewallIPSecExemptionsAllowNeighborDiscovery(value *bool)()
    SetFirewallIPSecExemptionsAllowRouterDiscovery(value *bool)()
    SetFirewallIPSecExemptionsNone(value *bool)()
    SetFirewallMergeKeyingModuleSettings(value *bool)()
    SetFirewallPacketQueueingMethod(value *FirewallPacketQueueingMethodType)()
    SetFirewallPreSharedKeyEncodingMethod(value *FirewallPreSharedKeyEncodingMethodType)()
    SetFirewallProfileDomain(value WindowsFirewallNetworkProfileable)()
    SetFirewallProfilePrivate(value WindowsFirewallNetworkProfileable)()
    SetFirewallProfilePublic(value WindowsFirewallNetworkProfileable)()
    SetFirewallRules(value []WindowsFirewallRuleable)()
    SetLanManagerAuthenticationLevel(value *LanManagerAuthenticationLevel)()
    SetLanManagerWorkstationDisableInsecureGuestLogons(value *bool)()
    SetLocalSecurityOptionsAdministratorAccountName(value *string)()
    SetLocalSecurityOptionsAdministratorElevationPromptBehavior(value *LocalSecurityOptionsAdministratorElevationPromptBehaviorType)()
    SetLocalSecurityOptionsAllowAnonymousEnumerationOfSAMAccountsAndShares(value *bool)()
    SetLocalSecurityOptionsAllowPKU2UAuthenticationRequests(value *bool)()
    SetLocalSecurityOptionsAllowRemoteCallsToSecurityAccountsManager(value *string)()
    SetLocalSecurityOptionsAllowRemoteCallsToSecurityAccountsManagerHelperBool(value *bool)()
    SetLocalSecurityOptionsAllowSystemToBeShutDownWithoutHavingToLogOn(value *bool)()
    SetLocalSecurityOptionsAllowUIAccessApplicationElevation(value *bool)()
    SetLocalSecurityOptionsAllowUIAccessApplicationsForSecureLocations(value *bool)()
    SetLocalSecurityOptionsAllowUndockWithoutHavingToLogon(value *bool)()
    SetLocalSecurityOptionsBlockMicrosoftAccounts(value *bool)()
    SetLocalSecurityOptionsBlockRemoteLogonWithBlankPassword(value *bool)()
    SetLocalSecurityOptionsBlockRemoteOpticalDriveAccess(value *bool)()
    SetLocalSecurityOptionsBlockUsersInstallingPrinterDrivers(value *bool)()
    SetLocalSecurityOptionsClearVirtualMemoryPageFile(value *bool)()
    SetLocalSecurityOptionsClientDigitallySignCommunicationsAlways(value *bool)()
    SetLocalSecurityOptionsClientSendUnencryptedPasswordToThirdPartySMBServers(value *bool)()
    SetLocalSecurityOptionsDetectApplicationInstallationsAndPromptForElevation(value *bool)()
    SetLocalSecurityOptionsDisableAdministratorAccount(value *bool)()
    SetLocalSecurityOptionsDisableClientDigitallySignCommunicationsIfServerAgrees(value *bool)()
    SetLocalSecurityOptionsDisableGuestAccount(value *bool)()
    SetLocalSecurityOptionsDisableServerDigitallySignCommunicationsAlways(value *bool)()
    SetLocalSecurityOptionsDisableServerDigitallySignCommunicationsIfClientAgrees(value *bool)()
    SetLocalSecurityOptionsDoNotAllowAnonymousEnumerationOfSAMAccounts(value *bool)()
    SetLocalSecurityOptionsDoNotRequireCtrlAltDel(value *bool)()
    SetLocalSecurityOptionsDoNotStoreLANManagerHashValueOnNextPasswordChange(value *bool)()
    SetLocalSecurityOptionsFormatAndEjectOfRemovableMediaAllowedUser(value *LocalSecurityOptionsFormatAndEjectOfRemovableMediaAllowedUserType)()
    SetLocalSecurityOptionsGuestAccountName(value *string)()
    SetLocalSecurityOptionsHideLastSignedInUser(value *bool)()
    SetLocalSecurityOptionsHideUsernameAtSignIn(value *bool)()
    SetLocalSecurityOptionsInformationDisplayedOnLockScreen(value *LocalSecurityOptionsInformationDisplayedOnLockScreenType)()
    SetLocalSecurityOptionsInformationShownOnLockScreen(value *LocalSecurityOptionsInformationShownOnLockScreenType)()
    SetLocalSecurityOptionsLogOnMessageText(value *string)()
    SetLocalSecurityOptionsLogOnMessageTitle(value *string)()
    SetLocalSecurityOptionsMachineInactivityLimit(value *int32)()
    SetLocalSecurityOptionsMachineInactivityLimitInMinutes(value *int32)()
    SetLocalSecurityOptionsMinimumSessionSecurityForNtlmSspBasedClients(value *LocalSecurityOptionsMinimumSessionSecurity)()
    SetLocalSecurityOptionsMinimumSessionSecurityForNtlmSspBasedServers(value *LocalSecurityOptionsMinimumSessionSecurity)()
    SetLocalSecurityOptionsOnlyElevateSignedExecutables(value *bool)()
    SetLocalSecurityOptionsRestrictAnonymousAccessToNamedPipesAndShares(value *bool)()
    SetLocalSecurityOptionsSmartCardRemovalBehavior(value *LocalSecurityOptionsSmartCardRemovalBehaviorType)()
    SetLocalSecurityOptionsStandardUserElevationPromptBehavior(value *LocalSecurityOptionsStandardUserElevationPromptBehaviorType)()
    SetLocalSecurityOptionsSwitchToSecureDesktopWhenPromptingForElevation(value *bool)()
    SetLocalSecurityOptionsUseAdminApprovalMode(value *bool)()
    SetLocalSecurityOptionsUseAdminApprovalModeForAdministrators(value *bool)()
    SetLocalSecurityOptionsVirtualizeFileAndRegistryWriteFailuresToPerUserLocations(value *bool)()
    SetSmartScreenBlockOverrideForFiles(value *bool)()
    SetSmartScreenEnableInShell(value *bool)()
    SetUserRightsAccessCredentialManagerAsTrustedCaller(value DeviceManagementUserRightsSettingable)()
    SetUserRightsActAsPartOfTheOperatingSystem(value DeviceManagementUserRightsSettingable)()
    SetUserRightsAllowAccessFromNetwork(value DeviceManagementUserRightsSettingable)()
    SetUserRightsBackupData(value DeviceManagementUserRightsSettingable)()
    SetUserRightsBlockAccessFromNetwork(value DeviceManagementUserRightsSettingable)()
    SetUserRightsChangeSystemTime(value DeviceManagementUserRightsSettingable)()
    SetUserRightsCreateGlobalObjects(value DeviceManagementUserRightsSettingable)()
    SetUserRightsCreatePageFile(value DeviceManagementUserRightsSettingable)()
    SetUserRightsCreatePermanentSharedObjects(value DeviceManagementUserRightsSettingable)()
    SetUserRightsCreateSymbolicLinks(value DeviceManagementUserRightsSettingable)()
    SetUserRightsCreateToken(value DeviceManagementUserRightsSettingable)()
    SetUserRightsDebugPrograms(value DeviceManagementUserRightsSettingable)()
    SetUserRightsDelegation(value DeviceManagementUserRightsSettingable)()
    SetUserRightsDenyLocalLogOn(value DeviceManagementUserRightsSettingable)()
    SetUserRightsGenerateSecurityAudits(value DeviceManagementUserRightsSettingable)()
    SetUserRightsImpersonateClient(value DeviceManagementUserRightsSettingable)()
    SetUserRightsIncreaseSchedulingPriority(value DeviceManagementUserRightsSettingable)()
    SetUserRightsLoadUnloadDrivers(value DeviceManagementUserRightsSettingable)()
    SetUserRightsLocalLogOn(value DeviceManagementUserRightsSettingable)()
    SetUserRightsLockMemory(value DeviceManagementUserRightsSettingable)()
    SetUserRightsManageAuditingAndSecurityLogs(value DeviceManagementUserRightsSettingable)()
    SetUserRightsManageVolumes(value DeviceManagementUserRightsSettingable)()
    SetUserRightsModifyFirmwareEnvironment(value DeviceManagementUserRightsSettingable)()
    SetUserRightsModifyObjectLabels(value DeviceManagementUserRightsSettingable)()
    SetUserRightsProfileSingleProcess(value DeviceManagementUserRightsSettingable)()
    SetUserRightsRemoteDesktopServicesLogOn(value DeviceManagementUserRightsSettingable)()
    SetUserRightsRemoteShutdown(value DeviceManagementUserRightsSettingable)()
    SetUserRightsRestoreData(value DeviceManagementUserRightsSettingable)()
    SetUserRightsTakeOwnership(value DeviceManagementUserRightsSettingable)()
    SetWindowsDefenderTamperProtection(value *WindowsDefenderTamperProtectionOptions)()
    SetXboxServicesAccessoryManagementServiceStartupMode(value *ServiceStartType)()
    SetXboxServicesEnableXboxGameSaveTask(value *bool)()
    SetXboxServicesLiveAuthManagerServiceStartupMode(value *ServiceStartType)()
    SetXboxServicesLiveGameSaveServiceStartupMode(value *ServiceStartType)()
    SetXboxServicesLiveNetworkingServiceStartupMode(value *ServiceStartType)()
}
