package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Windows10CompliancePolicyable 
type Windows10CompliancePolicyable interface {
    DeviceCompliancePolicyable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActiveFirewallRequired()(*bool)
    GetAntiSpywareRequired()(*bool)
    GetAntivirusRequired()(*bool)
    GetBitLockerEnabled()(*bool)
    GetCodeIntegrityEnabled()(*bool)
    GetConfigurationManagerComplianceRequired()(*bool)
    GetDefenderEnabled()(*bool)
    GetDefenderVersion()(*string)
    GetDeviceCompliancePolicyScript()(DeviceCompliancePolicyScriptable)
    GetDeviceThreatProtectionEnabled()(*bool)
    GetDeviceThreatProtectionRequiredSecurityLevel()(*DeviceThreatProtectionLevel)
    GetEarlyLaunchAntiMalwareDriverEnabled()(*bool)
    GetMobileOsMaximumVersion()(*string)
    GetMobileOsMinimumVersion()(*string)
    GetOsMaximumVersion()(*string)
    GetOsMinimumVersion()(*string)
    GetPasswordBlockSimple()(*bool)
    GetPasswordExpirationDays()(*int32)
    GetPasswordMinimumCharacterSetCount()(*int32)
    GetPasswordMinimumLength()(*int32)
    GetPasswordMinutesOfInactivityBeforeLock()(*int32)
    GetPasswordPreviousPasswordBlockCount()(*int32)
    GetPasswordRequired()(*bool)
    GetPasswordRequiredToUnlockFromIdle()(*bool)
    GetPasswordRequiredType()(*RequiredPasswordType)
    GetRequireHealthyDeviceReport()(*bool)
    GetRtpEnabled()(*bool)
    GetSecureBootEnabled()(*bool)
    GetSignatureOutOfDate()(*bool)
    GetStorageRequireEncryption()(*bool)
    GetTpmRequired()(*bool)
    GetValidOperatingSystemBuildRanges()([]OperatingSystemVersionRangeable)
    SetActiveFirewallRequired(value *bool)()
    SetAntiSpywareRequired(value *bool)()
    SetAntivirusRequired(value *bool)()
    SetBitLockerEnabled(value *bool)()
    SetCodeIntegrityEnabled(value *bool)()
    SetConfigurationManagerComplianceRequired(value *bool)()
    SetDefenderEnabled(value *bool)()
    SetDefenderVersion(value *string)()
    SetDeviceCompliancePolicyScript(value DeviceCompliancePolicyScriptable)()
    SetDeviceThreatProtectionEnabled(value *bool)()
    SetDeviceThreatProtectionRequiredSecurityLevel(value *DeviceThreatProtectionLevel)()
    SetEarlyLaunchAntiMalwareDriverEnabled(value *bool)()
    SetMobileOsMaximumVersion(value *string)()
    SetMobileOsMinimumVersion(value *string)()
    SetOsMaximumVersion(value *string)()
    SetOsMinimumVersion(value *string)()
    SetPasswordBlockSimple(value *bool)()
    SetPasswordExpirationDays(value *int32)()
    SetPasswordMinimumCharacterSetCount(value *int32)()
    SetPasswordMinimumLength(value *int32)()
    SetPasswordMinutesOfInactivityBeforeLock(value *int32)()
    SetPasswordPreviousPasswordBlockCount(value *int32)()
    SetPasswordRequired(value *bool)()
    SetPasswordRequiredToUnlockFromIdle(value *bool)()
    SetPasswordRequiredType(value *RequiredPasswordType)()
    SetRequireHealthyDeviceReport(value *bool)()
    SetRtpEnabled(value *bool)()
    SetSecureBootEnabled(value *bool)()
    SetSignatureOutOfDate(value *bool)()
    SetStorageRequireEncryption(value *bool)()
    SetTpmRequired(value *bool)()
    SetValidOperatingSystemBuildRanges(value []OperatingSystemVersionRangeable)()
}
