package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Windows10GeneralConfigurationable 
type Windows10GeneralConfigurationable interface {
    DeviceConfigurationable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccountsBlockAddingNonMicrosoftAccountEmail()(*bool)
    GetActivateAppsWithVoice()(*Enablement)
    GetAntiTheftModeBlocked()(*bool)
    GetAppManagementMSIAllowUserControlOverInstall()(*bool)
    GetAppManagementMSIAlwaysInstallWithElevatedPrivileges()(*bool)
    GetAppManagementPackageFamilyNamesToLaunchAfterLogOn()([]string)
    GetAppsAllowTrustedAppsSideloading()(*StateManagementSetting)
    GetAppsBlockWindowsStoreOriginatedApps()(*bool)
    GetAuthenticationAllowSecondaryDevice()(*bool)
    GetAuthenticationPreferredAzureADTenantDomainName()(*string)
    GetAuthenticationWebSignIn()(*Enablement)
    GetBluetoothAllowedServices()([]string)
    GetBluetoothBlockAdvertising()(*bool)
    GetBluetoothBlockDiscoverableMode()(*bool)
    GetBluetoothBlocked()(*bool)
    GetBluetoothBlockPrePairing()(*bool)
    GetBluetoothBlockPromptedProximalConnections()(*bool)
    GetCameraBlocked()(*bool)
    GetCellularBlockDataWhenRoaming()(*bool)
    GetCellularBlockVpn()(*bool)
    GetCellularBlockVpnWhenRoaming()(*bool)
    GetCellularData()(*ConfigurationUsage)
    GetCertificatesBlockManualRootCertificateInstallation()(*bool)
    GetConfigureTimeZone()(*string)
    GetConnectedDevicesServiceBlocked()(*bool)
    GetCopyPasteBlocked()(*bool)
    GetCortanaBlocked()(*bool)
    GetCryptographyAllowFipsAlgorithmPolicy()(*bool)
    GetDataProtectionBlockDirectMemoryAccess()(*bool)
    GetDefenderBlockEndUserAccess()(*bool)
    GetDefenderBlockOnAccessProtection()(*bool)
    GetDefenderCloudBlockLevel()(*DefenderCloudBlockLevelType)
    GetDefenderCloudExtendedTimeout()(*int32)
    GetDefenderCloudExtendedTimeoutInSeconds()(*int32)
    GetDefenderDaysBeforeDeletingQuarantinedMalware()(*int32)
    GetDefenderDetectedMalwareActions()(DefenderDetectedMalwareActionsable)
    GetDefenderDisableCatchupFullScan()(*bool)
    GetDefenderDisableCatchupQuickScan()(*bool)
    GetDefenderFileExtensionsToExclude()([]string)
    GetDefenderFilesAndFoldersToExclude()([]string)
    GetDefenderMonitorFileActivity()(*DefenderMonitorFileActivity)
    GetDefenderPotentiallyUnwantedAppAction()(*DefenderPotentiallyUnwantedAppAction)
    GetDefenderPotentiallyUnwantedAppActionSetting()(*DefenderProtectionType)
    GetDefenderProcessesToExclude()([]string)
    GetDefenderPromptForSampleSubmission()(*DefenderPromptForSampleSubmission)
    GetDefenderRequireBehaviorMonitoring()(*bool)
    GetDefenderRequireCloudProtection()(*bool)
    GetDefenderRequireNetworkInspectionSystem()(*bool)
    GetDefenderRequireRealTimeMonitoring()(*bool)
    GetDefenderScanArchiveFiles()(*bool)
    GetDefenderScanDownloads()(*bool)
    GetDefenderScanIncomingMail()(*bool)
    GetDefenderScanMappedNetworkDrivesDuringFullScan()(*bool)
    GetDefenderScanMaxCpu()(*int32)
    GetDefenderScanNetworkFiles()(*bool)
    GetDefenderScanRemovableDrivesDuringFullScan()(*bool)
    GetDefenderScanScriptsLoadedInInternetExplorer()(*bool)
    GetDefenderScanType()(*DefenderScanType)
    GetDefenderScheduledQuickScanTime()(*i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.TimeOnly)
    GetDefenderScheduledScanTime()(*i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.TimeOnly)
    GetDefenderScheduleScanEnableLowCpuPriority()(*bool)
    GetDefenderSignatureUpdateIntervalInHours()(*int32)
    GetDefenderSubmitSamplesConsentType()(*DefenderSubmitSamplesConsentType)
    GetDefenderSystemScanSchedule()(*WeeklySchedule)
    GetDeveloperUnlockSetting()(*StateManagementSetting)
    GetDeviceManagementBlockFactoryResetOnMobile()(*bool)
    GetDeviceManagementBlockManualUnenroll()(*bool)
    GetDiagnosticsDataSubmissionMode()(*DiagnosticDataSubmissionMode)
    GetDisplayAppListWithGdiDPIScalingTurnedOff()([]string)
    GetDisplayAppListWithGdiDPIScalingTurnedOn()([]string)
    GetEdgeAllowStartPagesModification()(*bool)
    GetEdgeBlockAccessToAboutFlags()(*bool)
    GetEdgeBlockAddressBarDropdown()(*bool)
    GetEdgeBlockAutofill()(*bool)
    GetEdgeBlockCompatibilityList()(*bool)
    GetEdgeBlockDeveloperTools()(*bool)
    GetEdgeBlocked()(*bool)
    GetEdgeBlockEditFavorites()(*bool)
    GetEdgeBlockExtensions()(*bool)
    GetEdgeBlockFullScreenMode()(*bool)
    GetEdgeBlockInPrivateBrowsing()(*bool)
    GetEdgeBlockJavaScript()(*bool)
    GetEdgeBlockLiveTileDataCollection()(*bool)
    GetEdgeBlockPasswordManager()(*bool)
    GetEdgeBlockPopups()(*bool)
    GetEdgeBlockPrelaunch()(*bool)
    GetEdgeBlockPrinting()(*bool)
    GetEdgeBlockSavingHistory()(*bool)
    GetEdgeBlockSearchEngineCustomization()(*bool)
    GetEdgeBlockSearchSuggestions()(*bool)
    GetEdgeBlockSendingDoNotTrackHeader()(*bool)
    GetEdgeBlockSendingIntranetTrafficToInternetExplorer()(*bool)
    GetEdgeBlockSideloadingExtensions()(*bool)
    GetEdgeBlockTabPreloading()(*bool)
    GetEdgeBlockWebContentOnNewTabPage()(*bool)
    GetEdgeClearBrowsingDataOnExit()(*bool)
    GetEdgeCookiePolicy()(*EdgeCookiePolicy)
    GetEdgeDisableFirstRunPage()(*bool)
    GetEdgeEnterpriseModeSiteListLocation()(*string)
    GetEdgeFavoritesBarVisibility()(*VisibilitySetting)
    GetEdgeFavoritesListLocation()(*string)
    GetEdgeFirstRunUrl()(*string)
    GetEdgeHomeButtonConfiguration()(EdgeHomeButtonConfigurationable)
    GetEdgeHomeButtonConfigurationEnabled()(*bool)
    GetEdgeHomepageUrls()([]string)
    GetEdgeKioskModeRestriction()(*EdgeKioskModeRestrictionType)
    GetEdgeKioskResetAfterIdleTimeInMinutes()(*int32)
    GetEdgeNewTabPageURL()(*string)
    GetEdgeOpensWith()(*EdgeOpenOptions)
    GetEdgePreventCertificateErrorOverride()(*bool)
    GetEdgeRequiredExtensionPackageFamilyNames()([]string)
    GetEdgeRequireSmartScreen()(*bool)
    GetEdgeSearchEngine()(EdgeSearchEngineBaseable)
    GetEdgeSendIntranetTrafficToInternetExplorer()(*bool)
    GetEdgeShowMessageWhenOpeningInternetExplorerSites()(*InternetExplorerMessageSetting)
    GetEdgeSyncFavoritesWithInternetExplorer()(*bool)
    GetEdgeTelemetryForMicrosoft365Analytics()(*EdgeTelemetryMode)
    GetEnableAutomaticRedeployment()(*bool)
    GetEnergySaverOnBatteryThresholdPercentage()(*int32)
    GetEnergySaverPluggedInThresholdPercentage()(*int32)
    GetEnterpriseCloudPrintDiscoveryEndPoint()(*string)
    GetEnterpriseCloudPrintDiscoveryMaxLimit()(*int32)
    GetEnterpriseCloudPrintMopriaDiscoveryResourceIdentifier()(*string)
    GetEnterpriseCloudPrintOAuthAuthority()(*string)
    GetEnterpriseCloudPrintOAuthClientIdentifier()(*string)
    GetEnterpriseCloudPrintResourceIdentifier()(*string)
    GetExperienceBlockDeviceDiscovery()(*bool)
    GetExperienceBlockErrorDialogWhenNoSIM()(*bool)
    GetExperienceBlockTaskSwitcher()(*bool)
    GetExperienceDoNotSyncBrowserSettings()(*BrowserSyncSetting)
    GetFindMyFiles()(*Enablement)
    GetGameDvrBlocked()(*bool)
    GetInkWorkspaceAccess()(*InkAccessSetting)
    GetInkWorkspaceAccessState()(*StateManagementSetting)
    GetInkWorkspaceBlockSuggestedApps()(*bool)
    GetInternetSharingBlocked()(*bool)
    GetLocationServicesBlocked()(*bool)
    GetLockScreenActivateAppsWithVoice()(*Enablement)
    GetLockScreenAllowTimeoutConfiguration()(*bool)
    GetLockScreenBlockActionCenterNotifications()(*bool)
    GetLockScreenBlockCortana()(*bool)
    GetLockScreenBlockToastNotifications()(*bool)
    GetLockScreenTimeoutInSeconds()(*int32)
    GetLogonBlockFastUserSwitching()(*bool)
    GetMessagingBlockMMS()(*bool)
    GetMessagingBlockRichCommunicationServices()(*bool)
    GetMessagingBlockSync()(*bool)
    GetMicrosoftAccountBlocked()(*bool)
    GetMicrosoftAccountBlockSettingsSync()(*bool)
    GetMicrosoftAccountSignInAssistantSettings()(*SignInAssistantOptions)
    GetNetworkProxyApplySettingsDeviceWide()(*bool)
    GetNetworkProxyAutomaticConfigurationUrl()(*string)
    GetNetworkProxyDisableAutoDetect()(*bool)
    GetNetworkProxyServer()(Windows10NetworkProxyServerable)
    GetNfcBlocked()(*bool)
    GetOneDriveDisableFileSync()(*bool)
    GetPasswordBlockSimple()(*bool)
    GetPasswordExpirationDays()(*int32)
    GetPasswordMinimumAgeInDays()(*int32)
    GetPasswordMinimumCharacterSetCount()(*int32)
    GetPasswordMinimumLength()(*int32)
    GetPasswordMinutesOfInactivityBeforeScreenTimeout()(*int32)
    GetPasswordPreviousPasswordBlockCount()(*int32)
    GetPasswordRequired()(*bool)
    GetPasswordRequiredType()(*RequiredPasswordType)
    GetPasswordRequireWhenResumeFromIdleState()(*bool)
    GetPasswordSignInFailureCountBeforeFactoryReset()(*int32)
    GetPersonalizationDesktopImageUrl()(*string)
    GetPersonalizationLockScreenImageUrl()(*string)
    GetPowerButtonActionOnBattery()(*PowerActionType)
    GetPowerButtonActionPluggedIn()(*PowerActionType)
    GetPowerHybridSleepOnBattery()(*Enablement)
    GetPowerHybridSleepPluggedIn()(*Enablement)
    GetPowerLidCloseActionOnBattery()(*PowerActionType)
    GetPowerLidCloseActionPluggedIn()(*PowerActionType)
    GetPowerSleepButtonActionOnBattery()(*PowerActionType)
    GetPowerSleepButtonActionPluggedIn()(*PowerActionType)
    GetPrinterBlockAddition()(*bool)
    GetPrinterDefaultName()(*string)
    GetPrinterNames()([]string)
    GetPrivacyAccessControls()([]WindowsPrivacyDataAccessControlItemable)
    GetPrivacyAdvertisingId()(*StateManagementSetting)
    GetPrivacyAutoAcceptPairingAndConsentPrompts()(*bool)
    GetPrivacyBlockActivityFeed()(*bool)
    GetPrivacyBlockInputPersonalization()(*bool)
    GetPrivacyBlockPublishUserActivities()(*bool)
    GetPrivacyDisableLaunchExperience()(*bool)
    GetResetProtectionModeBlocked()(*bool)
    GetSafeSearchFilter()(*SafeSearchFilterType)
    GetScreenCaptureBlocked()(*bool)
    GetSearchBlockDiacritics()(*bool)
    GetSearchBlockWebResults()(*bool)
    GetSearchDisableAutoLanguageDetection()(*bool)
    GetSearchDisableIndexerBackoff()(*bool)
    GetSearchDisableIndexingEncryptedItems()(*bool)
    GetSearchDisableIndexingRemovableDrive()(*bool)
    GetSearchDisableLocation()(*bool)
    GetSearchDisableUseLocation()(*bool)
    GetSearchEnableAutomaticIndexSizeManangement()(*bool)
    GetSearchEnableRemoteQueries()(*bool)
    GetSecurityBlockAzureADJoinedDevicesAutoEncryption()(*bool)
    GetSettingsBlockAccountsPage()(*bool)
    GetSettingsBlockAddProvisioningPackage()(*bool)
    GetSettingsBlockAppsPage()(*bool)
    GetSettingsBlockChangeLanguage()(*bool)
    GetSettingsBlockChangePowerSleep()(*bool)
    GetSettingsBlockChangeRegion()(*bool)
    GetSettingsBlockChangeSystemTime()(*bool)
    GetSettingsBlockDevicesPage()(*bool)
    GetSettingsBlockEaseOfAccessPage()(*bool)
    GetSettingsBlockEditDeviceName()(*bool)
    GetSettingsBlockGamingPage()(*bool)
    GetSettingsBlockNetworkInternetPage()(*bool)
    GetSettingsBlockPersonalizationPage()(*bool)
    GetSettingsBlockPrivacyPage()(*bool)
    GetSettingsBlockRemoveProvisioningPackage()(*bool)
    GetSettingsBlockSettingsApp()(*bool)
    GetSettingsBlockSystemPage()(*bool)
    GetSettingsBlockTimeLanguagePage()(*bool)
    GetSettingsBlockUpdateSecurityPage()(*bool)
    GetSharedUserAppDataAllowed()(*bool)
    GetSmartScreenAppInstallControl()(*AppInstallControlType)
    GetSmartScreenBlockPromptOverride()(*bool)
    GetSmartScreenBlockPromptOverrideForFiles()(*bool)
    GetSmartScreenEnableAppInstallControl()(*bool)
    GetStartBlockUnpinningAppsFromTaskbar()(*bool)
    GetStartMenuAppListVisibility()(*WindowsStartMenuAppListVisibilityType)
    GetStartMenuHideChangeAccountSettings()(*bool)
    GetStartMenuHideFrequentlyUsedApps()(*bool)
    GetStartMenuHideHibernate()(*bool)
    GetStartMenuHideLock()(*bool)
    GetStartMenuHidePowerButton()(*bool)
    GetStartMenuHideRecentJumpLists()(*bool)
    GetStartMenuHideRecentlyAddedApps()(*bool)
    GetStartMenuHideRestartOptions()(*bool)
    GetStartMenuHideShutDown()(*bool)
    GetStartMenuHideSignOut()(*bool)
    GetStartMenuHideSleep()(*bool)
    GetStartMenuHideSwitchAccount()(*bool)
    GetStartMenuHideUserTile()(*bool)
    GetStartMenuLayoutEdgeAssetsXml()([]byte)
    GetStartMenuLayoutXml()([]byte)
    GetStartMenuMode()(*WindowsStartMenuModeType)
    GetStartMenuPinnedFolderDocuments()(*VisibilitySetting)
    GetStartMenuPinnedFolderDownloads()(*VisibilitySetting)
    GetStartMenuPinnedFolderFileExplorer()(*VisibilitySetting)
    GetStartMenuPinnedFolderHomeGroup()(*VisibilitySetting)
    GetStartMenuPinnedFolderMusic()(*VisibilitySetting)
    GetStartMenuPinnedFolderNetwork()(*VisibilitySetting)
    GetStartMenuPinnedFolderPersonalFolder()(*VisibilitySetting)
    GetStartMenuPinnedFolderPictures()(*VisibilitySetting)
    GetStartMenuPinnedFolderSettings()(*VisibilitySetting)
    GetStartMenuPinnedFolderVideos()(*VisibilitySetting)
    GetStorageBlockRemovableStorage()(*bool)
    GetStorageRequireMobileDeviceEncryption()(*bool)
    GetStorageRestrictAppDataToSystemVolume()(*bool)
    GetStorageRestrictAppInstallToSystemVolume()(*bool)
    GetSystemTelemetryProxyServer()(*string)
    GetTaskManagerBlockEndTask()(*bool)
    GetTenantLockdownRequireNetworkDuringOutOfBoxExperience()(*bool)
    GetUninstallBuiltInApps()(*bool)
    GetUsbBlocked()(*bool)
    GetVoiceRecordingBlocked()(*bool)
    GetWebRtcBlockLocalhostIpAddress()(*bool)
    GetWiFiBlockAutomaticConnectHotspots()(*bool)
    GetWiFiBlocked()(*bool)
    GetWiFiBlockManualConfiguration()(*bool)
    GetWiFiScanInterval()(*int32)
    GetWindows10AppsForceUpdateSchedule()(Windows10AppsForceUpdateScheduleable)
    GetWindowsSpotlightBlockConsumerSpecificFeatures()(*bool)
    GetWindowsSpotlightBlocked()(*bool)
    GetWindowsSpotlightBlockOnActionCenter()(*bool)
    GetWindowsSpotlightBlockTailoredExperiences()(*bool)
    GetWindowsSpotlightBlockThirdPartyNotifications()(*bool)
    GetWindowsSpotlightBlockWelcomeExperience()(*bool)
    GetWindowsSpotlightBlockWindowsTips()(*bool)
    GetWindowsSpotlightConfigureOnLockScreen()(*WindowsSpotlightEnablementSettings)
    GetWindowsStoreBlockAutoUpdate()(*bool)
    GetWindowsStoreBlocked()(*bool)
    GetWindowsStoreEnablePrivateStoreOnly()(*bool)
    GetWirelessDisplayBlockProjectionToThisDevice()(*bool)
    GetWirelessDisplayBlockUserInputFromReceiver()(*bool)
    GetWirelessDisplayRequirePinForPairing()(*bool)
    SetAccountsBlockAddingNonMicrosoftAccountEmail(value *bool)()
    SetActivateAppsWithVoice(value *Enablement)()
    SetAntiTheftModeBlocked(value *bool)()
    SetAppManagementMSIAllowUserControlOverInstall(value *bool)()
    SetAppManagementMSIAlwaysInstallWithElevatedPrivileges(value *bool)()
    SetAppManagementPackageFamilyNamesToLaunchAfterLogOn(value []string)()
    SetAppsAllowTrustedAppsSideloading(value *StateManagementSetting)()
    SetAppsBlockWindowsStoreOriginatedApps(value *bool)()
    SetAuthenticationAllowSecondaryDevice(value *bool)()
    SetAuthenticationPreferredAzureADTenantDomainName(value *string)()
    SetAuthenticationWebSignIn(value *Enablement)()
    SetBluetoothAllowedServices(value []string)()
    SetBluetoothBlockAdvertising(value *bool)()
    SetBluetoothBlockDiscoverableMode(value *bool)()
    SetBluetoothBlocked(value *bool)()
    SetBluetoothBlockPrePairing(value *bool)()
    SetBluetoothBlockPromptedProximalConnections(value *bool)()
    SetCameraBlocked(value *bool)()
    SetCellularBlockDataWhenRoaming(value *bool)()
    SetCellularBlockVpn(value *bool)()
    SetCellularBlockVpnWhenRoaming(value *bool)()
    SetCellularData(value *ConfigurationUsage)()
    SetCertificatesBlockManualRootCertificateInstallation(value *bool)()
    SetConfigureTimeZone(value *string)()
    SetConnectedDevicesServiceBlocked(value *bool)()
    SetCopyPasteBlocked(value *bool)()
    SetCortanaBlocked(value *bool)()
    SetCryptographyAllowFipsAlgorithmPolicy(value *bool)()
    SetDataProtectionBlockDirectMemoryAccess(value *bool)()
    SetDefenderBlockEndUserAccess(value *bool)()
    SetDefenderBlockOnAccessProtection(value *bool)()
    SetDefenderCloudBlockLevel(value *DefenderCloudBlockLevelType)()
    SetDefenderCloudExtendedTimeout(value *int32)()
    SetDefenderCloudExtendedTimeoutInSeconds(value *int32)()
    SetDefenderDaysBeforeDeletingQuarantinedMalware(value *int32)()
    SetDefenderDetectedMalwareActions(value DefenderDetectedMalwareActionsable)()
    SetDefenderDisableCatchupFullScan(value *bool)()
    SetDefenderDisableCatchupQuickScan(value *bool)()
    SetDefenderFileExtensionsToExclude(value []string)()
    SetDefenderFilesAndFoldersToExclude(value []string)()
    SetDefenderMonitorFileActivity(value *DefenderMonitorFileActivity)()
    SetDefenderPotentiallyUnwantedAppAction(value *DefenderPotentiallyUnwantedAppAction)()
    SetDefenderPotentiallyUnwantedAppActionSetting(value *DefenderProtectionType)()
    SetDefenderProcessesToExclude(value []string)()
    SetDefenderPromptForSampleSubmission(value *DefenderPromptForSampleSubmission)()
    SetDefenderRequireBehaviorMonitoring(value *bool)()
    SetDefenderRequireCloudProtection(value *bool)()
    SetDefenderRequireNetworkInspectionSystem(value *bool)()
    SetDefenderRequireRealTimeMonitoring(value *bool)()
    SetDefenderScanArchiveFiles(value *bool)()
    SetDefenderScanDownloads(value *bool)()
    SetDefenderScanIncomingMail(value *bool)()
    SetDefenderScanMappedNetworkDrivesDuringFullScan(value *bool)()
    SetDefenderScanMaxCpu(value *int32)()
    SetDefenderScanNetworkFiles(value *bool)()
    SetDefenderScanRemovableDrivesDuringFullScan(value *bool)()
    SetDefenderScanScriptsLoadedInInternetExplorer(value *bool)()
    SetDefenderScanType(value *DefenderScanType)()
    SetDefenderScheduledQuickScanTime(value *i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.TimeOnly)()
    SetDefenderScheduledScanTime(value *i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.TimeOnly)()
    SetDefenderScheduleScanEnableLowCpuPriority(value *bool)()
    SetDefenderSignatureUpdateIntervalInHours(value *int32)()
    SetDefenderSubmitSamplesConsentType(value *DefenderSubmitSamplesConsentType)()
    SetDefenderSystemScanSchedule(value *WeeklySchedule)()
    SetDeveloperUnlockSetting(value *StateManagementSetting)()
    SetDeviceManagementBlockFactoryResetOnMobile(value *bool)()
    SetDeviceManagementBlockManualUnenroll(value *bool)()
    SetDiagnosticsDataSubmissionMode(value *DiagnosticDataSubmissionMode)()
    SetDisplayAppListWithGdiDPIScalingTurnedOff(value []string)()
    SetDisplayAppListWithGdiDPIScalingTurnedOn(value []string)()
    SetEdgeAllowStartPagesModification(value *bool)()
    SetEdgeBlockAccessToAboutFlags(value *bool)()
    SetEdgeBlockAddressBarDropdown(value *bool)()
    SetEdgeBlockAutofill(value *bool)()
    SetEdgeBlockCompatibilityList(value *bool)()
    SetEdgeBlockDeveloperTools(value *bool)()
    SetEdgeBlocked(value *bool)()
    SetEdgeBlockEditFavorites(value *bool)()
    SetEdgeBlockExtensions(value *bool)()
    SetEdgeBlockFullScreenMode(value *bool)()
    SetEdgeBlockInPrivateBrowsing(value *bool)()
    SetEdgeBlockJavaScript(value *bool)()
    SetEdgeBlockLiveTileDataCollection(value *bool)()
    SetEdgeBlockPasswordManager(value *bool)()
    SetEdgeBlockPopups(value *bool)()
    SetEdgeBlockPrelaunch(value *bool)()
    SetEdgeBlockPrinting(value *bool)()
    SetEdgeBlockSavingHistory(value *bool)()
    SetEdgeBlockSearchEngineCustomization(value *bool)()
    SetEdgeBlockSearchSuggestions(value *bool)()
    SetEdgeBlockSendingDoNotTrackHeader(value *bool)()
    SetEdgeBlockSendingIntranetTrafficToInternetExplorer(value *bool)()
    SetEdgeBlockSideloadingExtensions(value *bool)()
    SetEdgeBlockTabPreloading(value *bool)()
    SetEdgeBlockWebContentOnNewTabPage(value *bool)()
    SetEdgeClearBrowsingDataOnExit(value *bool)()
    SetEdgeCookiePolicy(value *EdgeCookiePolicy)()
    SetEdgeDisableFirstRunPage(value *bool)()
    SetEdgeEnterpriseModeSiteListLocation(value *string)()
    SetEdgeFavoritesBarVisibility(value *VisibilitySetting)()
    SetEdgeFavoritesListLocation(value *string)()
    SetEdgeFirstRunUrl(value *string)()
    SetEdgeHomeButtonConfiguration(value EdgeHomeButtonConfigurationable)()
    SetEdgeHomeButtonConfigurationEnabled(value *bool)()
    SetEdgeHomepageUrls(value []string)()
    SetEdgeKioskModeRestriction(value *EdgeKioskModeRestrictionType)()
    SetEdgeKioskResetAfterIdleTimeInMinutes(value *int32)()
    SetEdgeNewTabPageURL(value *string)()
    SetEdgeOpensWith(value *EdgeOpenOptions)()
    SetEdgePreventCertificateErrorOverride(value *bool)()
    SetEdgeRequiredExtensionPackageFamilyNames(value []string)()
    SetEdgeRequireSmartScreen(value *bool)()
    SetEdgeSearchEngine(value EdgeSearchEngineBaseable)()
    SetEdgeSendIntranetTrafficToInternetExplorer(value *bool)()
    SetEdgeShowMessageWhenOpeningInternetExplorerSites(value *InternetExplorerMessageSetting)()
    SetEdgeSyncFavoritesWithInternetExplorer(value *bool)()
    SetEdgeTelemetryForMicrosoft365Analytics(value *EdgeTelemetryMode)()
    SetEnableAutomaticRedeployment(value *bool)()
    SetEnergySaverOnBatteryThresholdPercentage(value *int32)()
    SetEnergySaverPluggedInThresholdPercentage(value *int32)()
    SetEnterpriseCloudPrintDiscoveryEndPoint(value *string)()
    SetEnterpriseCloudPrintDiscoveryMaxLimit(value *int32)()
    SetEnterpriseCloudPrintMopriaDiscoveryResourceIdentifier(value *string)()
    SetEnterpriseCloudPrintOAuthAuthority(value *string)()
    SetEnterpriseCloudPrintOAuthClientIdentifier(value *string)()
    SetEnterpriseCloudPrintResourceIdentifier(value *string)()
    SetExperienceBlockDeviceDiscovery(value *bool)()
    SetExperienceBlockErrorDialogWhenNoSIM(value *bool)()
    SetExperienceBlockTaskSwitcher(value *bool)()
    SetExperienceDoNotSyncBrowserSettings(value *BrowserSyncSetting)()
    SetFindMyFiles(value *Enablement)()
    SetGameDvrBlocked(value *bool)()
    SetInkWorkspaceAccess(value *InkAccessSetting)()
    SetInkWorkspaceAccessState(value *StateManagementSetting)()
    SetInkWorkspaceBlockSuggestedApps(value *bool)()
    SetInternetSharingBlocked(value *bool)()
    SetLocationServicesBlocked(value *bool)()
    SetLockScreenActivateAppsWithVoice(value *Enablement)()
    SetLockScreenAllowTimeoutConfiguration(value *bool)()
    SetLockScreenBlockActionCenterNotifications(value *bool)()
    SetLockScreenBlockCortana(value *bool)()
    SetLockScreenBlockToastNotifications(value *bool)()
    SetLockScreenTimeoutInSeconds(value *int32)()
    SetLogonBlockFastUserSwitching(value *bool)()
    SetMessagingBlockMMS(value *bool)()
    SetMessagingBlockRichCommunicationServices(value *bool)()
    SetMessagingBlockSync(value *bool)()
    SetMicrosoftAccountBlocked(value *bool)()
    SetMicrosoftAccountBlockSettingsSync(value *bool)()
    SetMicrosoftAccountSignInAssistantSettings(value *SignInAssistantOptions)()
    SetNetworkProxyApplySettingsDeviceWide(value *bool)()
    SetNetworkProxyAutomaticConfigurationUrl(value *string)()
    SetNetworkProxyDisableAutoDetect(value *bool)()
    SetNetworkProxyServer(value Windows10NetworkProxyServerable)()
    SetNfcBlocked(value *bool)()
    SetOneDriveDisableFileSync(value *bool)()
    SetPasswordBlockSimple(value *bool)()
    SetPasswordExpirationDays(value *int32)()
    SetPasswordMinimumAgeInDays(value *int32)()
    SetPasswordMinimumCharacterSetCount(value *int32)()
    SetPasswordMinimumLength(value *int32)()
    SetPasswordMinutesOfInactivityBeforeScreenTimeout(value *int32)()
    SetPasswordPreviousPasswordBlockCount(value *int32)()
    SetPasswordRequired(value *bool)()
    SetPasswordRequiredType(value *RequiredPasswordType)()
    SetPasswordRequireWhenResumeFromIdleState(value *bool)()
    SetPasswordSignInFailureCountBeforeFactoryReset(value *int32)()
    SetPersonalizationDesktopImageUrl(value *string)()
    SetPersonalizationLockScreenImageUrl(value *string)()
    SetPowerButtonActionOnBattery(value *PowerActionType)()
    SetPowerButtonActionPluggedIn(value *PowerActionType)()
    SetPowerHybridSleepOnBattery(value *Enablement)()
    SetPowerHybridSleepPluggedIn(value *Enablement)()
    SetPowerLidCloseActionOnBattery(value *PowerActionType)()
    SetPowerLidCloseActionPluggedIn(value *PowerActionType)()
    SetPowerSleepButtonActionOnBattery(value *PowerActionType)()
    SetPowerSleepButtonActionPluggedIn(value *PowerActionType)()
    SetPrinterBlockAddition(value *bool)()
    SetPrinterDefaultName(value *string)()
    SetPrinterNames(value []string)()
    SetPrivacyAccessControls(value []WindowsPrivacyDataAccessControlItemable)()
    SetPrivacyAdvertisingId(value *StateManagementSetting)()
    SetPrivacyAutoAcceptPairingAndConsentPrompts(value *bool)()
    SetPrivacyBlockActivityFeed(value *bool)()
    SetPrivacyBlockInputPersonalization(value *bool)()
    SetPrivacyBlockPublishUserActivities(value *bool)()
    SetPrivacyDisableLaunchExperience(value *bool)()
    SetResetProtectionModeBlocked(value *bool)()
    SetSafeSearchFilter(value *SafeSearchFilterType)()
    SetScreenCaptureBlocked(value *bool)()
    SetSearchBlockDiacritics(value *bool)()
    SetSearchBlockWebResults(value *bool)()
    SetSearchDisableAutoLanguageDetection(value *bool)()
    SetSearchDisableIndexerBackoff(value *bool)()
    SetSearchDisableIndexingEncryptedItems(value *bool)()
    SetSearchDisableIndexingRemovableDrive(value *bool)()
    SetSearchDisableLocation(value *bool)()
    SetSearchDisableUseLocation(value *bool)()
    SetSearchEnableAutomaticIndexSizeManangement(value *bool)()
    SetSearchEnableRemoteQueries(value *bool)()
    SetSecurityBlockAzureADJoinedDevicesAutoEncryption(value *bool)()
    SetSettingsBlockAccountsPage(value *bool)()
    SetSettingsBlockAddProvisioningPackage(value *bool)()
    SetSettingsBlockAppsPage(value *bool)()
    SetSettingsBlockChangeLanguage(value *bool)()
    SetSettingsBlockChangePowerSleep(value *bool)()
    SetSettingsBlockChangeRegion(value *bool)()
    SetSettingsBlockChangeSystemTime(value *bool)()
    SetSettingsBlockDevicesPage(value *bool)()
    SetSettingsBlockEaseOfAccessPage(value *bool)()
    SetSettingsBlockEditDeviceName(value *bool)()
    SetSettingsBlockGamingPage(value *bool)()
    SetSettingsBlockNetworkInternetPage(value *bool)()
    SetSettingsBlockPersonalizationPage(value *bool)()
    SetSettingsBlockPrivacyPage(value *bool)()
    SetSettingsBlockRemoveProvisioningPackage(value *bool)()
    SetSettingsBlockSettingsApp(value *bool)()
    SetSettingsBlockSystemPage(value *bool)()
    SetSettingsBlockTimeLanguagePage(value *bool)()
    SetSettingsBlockUpdateSecurityPage(value *bool)()
    SetSharedUserAppDataAllowed(value *bool)()
    SetSmartScreenAppInstallControl(value *AppInstallControlType)()
    SetSmartScreenBlockPromptOverride(value *bool)()
    SetSmartScreenBlockPromptOverrideForFiles(value *bool)()
    SetSmartScreenEnableAppInstallControl(value *bool)()
    SetStartBlockUnpinningAppsFromTaskbar(value *bool)()
    SetStartMenuAppListVisibility(value *WindowsStartMenuAppListVisibilityType)()
    SetStartMenuHideChangeAccountSettings(value *bool)()
    SetStartMenuHideFrequentlyUsedApps(value *bool)()
    SetStartMenuHideHibernate(value *bool)()
    SetStartMenuHideLock(value *bool)()
    SetStartMenuHidePowerButton(value *bool)()
    SetStartMenuHideRecentJumpLists(value *bool)()
    SetStartMenuHideRecentlyAddedApps(value *bool)()
    SetStartMenuHideRestartOptions(value *bool)()
    SetStartMenuHideShutDown(value *bool)()
    SetStartMenuHideSignOut(value *bool)()
    SetStartMenuHideSleep(value *bool)()
    SetStartMenuHideSwitchAccount(value *bool)()
    SetStartMenuHideUserTile(value *bool)()
    SetStartMenuLayoutEdgeAssetsXml(value []byte)()
    SetStartMenuLayoutXml(value []byte)()
    SetStartMenuMode(value *WindowsStartMenuModeType)()
    SetStartMenuPinnedFolderDocuments(value *VisibilitySetting)()
    SetStartMenuPinnedFolderDownloads(value *VisibilitySetting)()
    SetStartMenuPinnedFolderFileExplorer(value *VisibilitySetting)()
    SetStartMenuPinnedFolderHomeGroup(value *VisibilitySetting)()
    SetStartMenuPinnedFolderMusic(value *VisibilitySetting)()
    SetStartMenuPinnedFolderNetwork(value *VisibilitySetting)()
    SetStartMenuPinnedFolderPersonalFolder(value *VisibilitySetting)()
    SetStartMenuPinnedFolderPictures(value *VisibilitySetting)()
    SetStartMenuPinnedFolderSettings(value *VisibilitySetting)()
    SetStartMenuPinnedFolderVideos(value *VisibilitySetting)()
    SetStorageBlockRemovableStorage(value *bool)()
    SetStorageRequireMobileDeviceEncryption(value *bool)()
    SetStorageRestrictAppDataToSystemVolume(value *bool)()
    SetStorageRestrictAppInstallToSystemVolume(value *bool)()
    SetSystemTelemetryProxyServer(value *string)()
    SetTaskManagerBlockEndTask(value *bool)()
    SetTenantLockdownRequireNetworkDuringOutOfBoxExperience(value *bool)()
    SetUninstallBuiltInApps(value *bool)()
    SetUsbBlocked(value *bool)()
    SetVoiceRecordingBlocked(value *bool)()
    SetWebRtcBlockLocalhostIpAddress(value *bool)()
    SetWiFiBlockAutomaticConnectHotspots(value *bool)()
    SetWiFiBlocked(value *bool)()
    SetWiFiBlockManualConfiguration(value *bool)()
    SetWiFiScanInterval(value *int32)()
    SetWindows10AppsForceUpdateSchedule(value Windows10AppsForceUpdateScheduleable)()
    SetWindowsSpotlightBlockConsumerSpecificFeatures(value *bool)()
    SetWindowsSpotlightBlocked(value *bool)()
    SetWindowsSpotlightBlockOnActionCenter(value *bool)()
    SetWindowsSpotlightBlockTailoredExperiences(value *bool)()
    SetWindowsSpotlightBlockThirdPartyNotifications(value *bool)()
    SetWindowsSpotlightBlockWelcomeExperience(value *bool)()
    SetWindowsSpotlightBlockWindowsTips(value *bool)()
    SetWindowsSpotlightConfigureOnLockScreen(value *WindowsSpotlightEnablementSettings)()
    SetWindowsStoreBlockAutoUpdate(value *bool)()
    SetWindowsStoreBlocked(value *bool)()
    SetWindowsStoreEnablePrivateStoreOnly(value *bool)()
    SetWirelessDisplayBlockProjectionToThisDevice(value *bool)()
    SetWirelessDisplayBlockUserInputFromReceiver(value *bool)()
    SetWirelessDisplayRequirePinForPairing(value *bool)()
}
