package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// WindowsManagedAppProtectionable 
type WindowsManagedAppProtectionable interface {
    ManagedAppPolicyable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAllowedInboundDataTransferSources()(*WindowsManagedAppDataTransferLevel)
    GetAllowedOutboundClipboardSharingLevel()(*WindowsManagedAppClipboardSharingLevel)
    GetAllowedOutboundDataTransferDestinations()(*WindowsManagedAppDataTransferLevel)
    GetAppActionIfUnableToAuthenticateUser()(*ManagedAppRemediationAction)
    GetApps()([]ManagedMobileAppable)
    GetAssignments()([]TargetedManagedAppPolicyAssignmentable)
    GetDeployedAppCount()(*int32)
    GetIsAssigned()(*bool)
    GetMaximumAllowedDeviceThreatLevel()(*ManagedAppDeviceThreatLevel)
    GetMaximumRequiredOsVersion()(*string)
    GetMaximumWarningOsVersion()(*string)
    GetMaximumWipeOsVersion()(*string)
    GetMinimumRequiredAppVersion()(*string)
    GetMinimumRequiredOsVersion()(*string)
    GetMinimumRequiredSdkVersion()(*string)
    GetMinimumWarningAppVersion()(*string)
    GetMinimumWarningOsVersion()(*string)
    GetMinimumWipeAppVersion()(*string)
    GetMinimumWipeOsVersion()(*string)
    GetMinimumWipeSdkVersion()(*string)
    GetMobileThreatDefenseRemediationAction()(*ManagedAppRemediationAction)
    GetPeriodOfflineBeforeAccessCheck()(*i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ISODuration)
    GetPeriodOfflineBeforeWipeIsEnforced()(*i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ISODuration)
    GetPrintBlocked()(*bool)
    SetAllowedInboundDataTransferSources(value *WindowsManagedAppDataTransferLevel)()
    SetAllowedOutboundClipboardSharingLevel(value *WindowsManagedAppClipboardSharingLevel)()
    SetAllowedOutboundDataTransferDestinations(value *WindowsManagedAppDataTransferLevel)()
    SetAppActionIfUnableToAuthenticateUser(value *ManagedAppRemediationAction)()
    SetApps(value []ManagedMobileAppable)()
    SetAssignments(value []TargetedManagedAppPolicyAssignmentable)()
    SetDeployedAppCount(value *int32)()
    SetIsAssigned(value *bool)()
    SetMaximumAllowedDeviceThreatLevel(value *ManagedAppDeviceThreatLevel)()
    SetMaximumRequiredOsVersion(value *string)()
    SetMaximumWarningOsVersion(value *string)()
    SetMaximumWipeOsVersion(value *string)()
    SetMinimumRequiredAppVersion(value *string)()
    SetMinimumRequiredOsVersion(value *string)()
    SetMinimumRequiredSdkVersion(value *string)()
    SetMinimumWarningAppVersion(value *string)()
    SetMinimumWarningOsVersion(value *string)()
    SetMinimumWipeAppVersion(value *string)()
    SetMinimumWipeOsVersion(value *string)()
    SetMinimumWipeSdkVersion(value *string)()
    SetMobileThreatDefenseRemediationAction(value *ManagedAppRemediationAction)()
    SetPeriodOfflineBeforeAccessCheck(value *i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ISODuration)()
    SetPeriodOfflineBeforeWipeIsEnforced(value *i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ISODuration)()
    SetPrintBlocked(value *bool)()
}
