package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// WindowsWiredNetworkConfigurationable 
type WindowsWiredNetworkConfigurationable interface {
    DeviceConfigurationable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAuthenticationBlockPeriodInMinutes()(*int32)
    GetAuthenticationMethod()(*WiredNetworkAuthenticationMethod)
    GetAuthenticationPeriodInSeconds()(*int32)
    GetAuthenticationRetryDelayPeriodInSeconds()(*int32)
    GetAuthenticationType()(*WiredNetworkAuthenticationType)
    GetCacheCredentials()(*bool)
    GetDisableUserPromptForServerValidation()(*bool)
    GetEapolStartPeriodInSeconds()(*int32)
    GetEapType()(*EapType)
    GetEnforce8021X()(*bool)
    GetForceFIPSCompliance()(*bool)
    GetIdentityCertificateForClientAuthentication()(WindowsCertificateProfileBaseable)
    GetInnerAuthenticationProtocolForEAPTTLS()(*NonEapAuthenticationMethodForEapTtlsType)
    GetMaximumAuthenticationFailures()(*int32)
    GetMaximumEAPOLStartMessages()(*int32)
    GetOuterIdentityPrivacyTemporaryValue()(*string)
    GetPerformServerValidation()(*bool)
    GetRequireCryptographicBinding()(*bool)
    GetRootCertificateForClientValidation()(Windows81TrustedRootCertificateable)
    GetRootCertificatesForServerValidation()([]Windows81TrustedRootCertificateable)
    GetSecondaryAuthenticationMethod()(*WiredNetworkAuthenticationMethod)
    GetSecondaryIdentityCertificateForClientAuthentication()(WindowsCertificateProfileBaseable)
    GetSecondaryRootCertificateForClientValidation()(Windows81TrustedRootCertificateable)
    GetTrustedServerCertificateNames()([]string)
    SetAuthenticationBlockPeriodInMinutes(value *int32)()
    SetAuthenticationMethod(value *WiredNetworkAuthenticationMethod)()
    SetAuthenticationPeriodInSeconds(value *int32)()
    SetAuthenticationRetryDelayPeriodInSeconds(value *int32)()
    SetAuthenticationType(value *WiredNetworkAuthenticationType)()
    SetCacheCredentials(value *bool)()
    SetDisableUserPromptForServerValidation(value *bool)()
    SetEapolStartPeriodInSeconds(value *int32)()
    SetEapType(value *EapType)()
    SetEnforce8021X(value *bool)()
    SetForceFIPSCompliance(value *bool)()
    SetIdentityCertificateForClientAuthentication(value WindowsCertificateProfileBaseable)()
    SetInnerAuthenticationProtocolForEAPTTLS(value *NonEapAuthenticationMethodForEapTtlsType)()
    SetMaximumAuthenticationFailures(value *int32)()
    SetMaximumEAPOLStartMessages(value *int32)()
    SetOuterIdentityPrivacyTemporaryValue(value *string)()
    SetPerformServerValidation(value *bool)()
    SetRequireCryptographicBinding(value *bool)()
    SetRootCertificateForClientValidation(value Windows81TrustedRootCertificateable)()
    SetRootCertificatesForServerValidation(value []Windows81TrustedRootCertificateable)()
    SetSecondaryAuthenticationMethod(value *WiredNetworkAuthenticationMethod)()
    SetSecondaryIdentityCertificateForClientAuthentication(value WindowsCertificateProfileBaseable)()
    SetSecondaryRootCertificateForClientValidation(value Windows81TrustedRootCertificateable)()
    SetTrustedServerCertificateNames(value []string)()
}
