name: Send a message to slack

inputs:
  job:
    descrption: passthrough for env.GITHUB_JOB
  msg:
    description: The slack message text
  ref:
    description: passthrough for env.GITHUB_REF
  run_id:
    description: passthrough for env.GITHUB_RUN_ID
  sha:
    description: passthrough for env.GITHUB_SHA
  slack_url:
    description: passthrough for secrets.SLACK_WEBHOOK_URL

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: set trimmable ref
      shell: bash
      run: |
        echo "github_reference=${{ github.ref }}" >> $GITHUB_ENV

    - name: trim ref
      shell: bash
      run: |
        echo "trimmed_ref=${github_reference#refs/}" >> $GITHUB_ENV

    - name: compose links
      shell: bash
      run: |
        echo "JOB=${{ github.job && format(' -:- ${0}', github.job) || ''}}" >> $GITHUB_ENV
        echo "LOGS=${{ github.run_id && format('<${0}/${1}/actions/runs/${2}|[Logs]>', github.server_url, github.repository, github.run_id) || '-'}}" >> $GITHUB_ENV
        echo "COMMIT=${{ github.sha && format('<${0}/${1}/commit/${2}|[Commit]>', github.server_url, github.repository, github.sha) || '-'}}" >> $GITHUB_ENV
        echo "REF=${{ env.trimmed_ref && format('<${0}/${1}/${2}|[Ref]>', github.server_url, github.repository, env.trimmed_ref) || '-'}}" >> $GITHUB_ENV

    - shell: bash
      run: |
        echo "-----"
        echo "jj ${{env.GITHUB_JOB}}"
        echo "rr ${{env.GITHUB_REF}}"
        echo "ss ${{env.GITHUB_SHA}}"
        echo "ii ${{env.GITHUB_RUN_ID}}"
        echo "-----"

    - id: slack-message
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "text": "${{ inputs.msg }} :: ${{ env.LOGS }} ${{ env.COMMIT }} ${{ env.REF }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ inputs.msg }}${{ env.JOB }}\n${{ env.LOGS }} ${{ env.COMMIT }} ${{ env.REF }}"
                }
              }
            ]
          }
