// Code generated by "stringer -type=optionIdentifier"; DO NOT EDIT.

package connector

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[folders-0]
	_ = x[messages-1]
	_ = x[users-2]
}

const _optionIdentifier_name = "foldersmessagesusers"

var _optionIdentifier_index = [...]uint8{0, 7, 15, 20}

func (i optionIdentifier) String() string {
	if i < 0 || i >= optionIdentifier(len(_optionIdentifier_index)-1) {
		return "optionIdentifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _optionIdentifier_name[_optionIdentifier_index[i]:_optionIdentifier_index[i+1]]
}
