// Code generated by "stringer -type=DataCategory"; DO NOT EDIT.

package sharepoint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[List-1]
	_ = x[Drive-2]
}

const _DataCategory_name = "UnknownListDrive"

var _DataCategory_index = [...]uint8{0, 7, 11, 16}

func (i DataCategory) String() string {
	if i < 0 || i >= DataCategory(len(_DataCategory_index)-1) {
		return "DataCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataCategory_name[_DataCategory_index[i]:_DataCategory_index[i+1]]
}
