// Code generated by "stringer -type=Target"; DO NOT EDIT.

package sharepoint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-1]
	_ = x[List-2]
	_ = x[Drive-3]
}

const _Target_name = "UnknownListDrive"

var _Target_index = [...]uint8{0, 7, 11, 16}

func (i Target) String() string {
	i -= 1
	if i < 0 || i >= Target(len(_Target_index)-1) {
		return "Target(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Target_name[_Target_index[i]:_Target_index[i+1]]
}
