name: Bug Report
description: File a Corso bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Corso Version?
      description: What version of Corso (`corso --version`) are you running?
      value: "Corso vX.X.X"
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: Where are you running Corso?
      description: Include OS version (e.g., macOS 13.0.1, Windows 11 Pro) and Object Storage system being used.
      placeholder: Also include addition system details if relevant (e.g., shell, antivirus, firewall/proxy used on the network, etc.)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please run Corso with `--log-level debug`.
      placeholder: This will be automatically formatted, so no need for backticks.
      render: shell
