// Code generated by "stringer -type=oneDriveCategory"; DO NOT EDIT.

package selectors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OneDriveCategoryUnknown-0]
	_ = x[OneDriveUser-1]
}

const _oneDriveCategory_name = "OneDriveCategoryUnknownOneDriveUser"

var _oneDriveCategory_index = [...]uint8{0, 23, 35}

func (i oneDriveCategory) String() string {
	if i < 0 || i >= oneDriveCategory(len(_oneDriveCategory_index)-1) {
		return "oneDriveCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _oneDriveCategory_name[_oneDriveCategory_index[i]:_oneDriveCategory_index[i+1]]
}
