// Code generated by "stringer -type=onedriveCategory"; DO NOT EDIT.

package selectors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OneDriveCategoryUnknown-0]
	_ = x[OneDriveUser-1]
}

const _onedriveCategory_name = "OneDriveCategoryUnknownOneDriveUser"

var _onedriveCategory_index = [...]uint8{0, 23, 35}

func (i onedriveCategory) String() string {
	if i < 0 || i >= onedriveCategory(len(_onedriveCategory_index)-1) {
		return "onedriveCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _onedriveCategory_name[_onedriveCategory_index[i]:_onedriveCategory_index[i+1]]
}
