// Code generated by "stringer -type=comparator -linecomment"; DO NOT EDIT.

package filters

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownComparator-0]
	_ = x[EqualTo-1]
	_ = x[GreaterThan-2]
	_ = x[LessThan-3]
	_ = x[TargetContains-4]
	_ = x[TargetIn-5]
	_ = x[Passes-6]
	_ = x[Fails-7]
	_ = x[IdentityValue-8]
	_ = x[TargetPrefixes-9]
	_ = x[TargetSuffixes-10]
	_ = x[TargetPathPrefix-11]
	_ = x[TargetPathContains-12]
	_ = x[TargetPathSuffix-13]
	_ = x[TargetPathEquals-14]
}

const _comparator_name = "UnknownComparisonEQGTLTContINPassFailIdentityPfxSfxPathPfxPathContPathSfxPathEQ"

var _comparator_index = [...]uint8{0, 17, 19, 21, 23, 27, 29, 33, 37, 45, 48, 51, 58, 66, 73, 79}

func (i comparator) String() string {
	if i < 0 || i >= comparator(len(_comparator_index)-1) {
		return "comparator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _comparator_name[_comparator_index[i]:_comparator_index[i+1]]
}
