// Code generated by "stringer -type=accountProvider -linecomment"; DO NOT EDIT.

package account

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProviderUnknown-0]
	_ = x[ProviderM365-1]
}

const _accountProvider_name = "Unknown ProviderM365"

var _accountProvider_index = [...]uint8{0, 16, 20}

func (i accountProvider) String() string {
	if i < 0 || i >= accountProvider(len(_accountProvider_index)-1) {
		return "accountProvider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _accountProvider_name[_accountProvider_index[i]:_accountProvider_index[i+1]]
}
