package tenantadmin

import (
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    ifda19816f54f079134d70c11e75d6b26799300cf72079e282f1d3bb9a6750354 "github.com/alcionai/corso/src/internal/connector/graph/betasdk/models"
)

// Settingsable 
type Settingsable interface {
    ifda19816f54f079134d70c11e75d6b26799300cf72079e282f1d3bb9a6750354.Entityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAllowedDomainGuidsForSyncApp()([]i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetAvailableManagedPathsForSiteCreation()([]string)
    GetDeletedUserPersonalSiteRetentionPeriodInDays()(*int32)
    GetExcludedFileExtensionsForSyncApp()([]string)
    GetIdleSessionSignOut()(IdleSessionSignOutable)
    GetImageTaggingOption()(*ImageTaggingChoice)
    GetIsCommentingOnSitePagesEnabled()(*bool)
    GetIsFileActivityNotificationEnabled()(*bool)
    GetIsLegacyAuthProtocolsEnabled()(*bool)
    GetIsLoopEnabled()(*bool)
    GetIsMacSyncAppEnabled()(*bool)
    GetIsRequireAcceptingUserToMatchInvitedUserEnabled()(*bool)
    GetIsResharingByExternalUsersEnabled()(*bool)
    GetIsSharePointMobileNotificationEnabled()(*bool)
    GetIsSharePointNewsfeedEnabled()(*bool)
    GetIsSiteCreationEnabled()(*bool)
    GetIsSiteCreationUIEnabled()(*bool)
    GetIsSitePagesCreationEnabled()(*bool)
    GetIsSitesStorageLimitAutomatic()(*bool)
    GetIsSyncButtonHiddenOnPersonalSite()(*bool)
    GetIsUnmanagedSyncAppForTenantRestricted()(*bool)
    GetPersonalSiteDefaultStorageLimitInMB()(*int64)
    GetSharingAllowedDomainList()([]string)
    GetSharingBlockedDomainList()([]string)
    GetSharingCapability()(*SharingCapabilities)
    GetSharingDomainRestrictionMode()(*SharingDomainRestrictionMode)
    GetSiteCreationDefaultManagedPath()(*string)
    GetSiteCreationDefaultStorageLimitInMB()(*int32)
    GetTenantDefaultTimezone()(*string)
    SetAllowedDomainGuidsForSyncApp(value []i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetAvailableManagedPathsForSiteCreation(value []string)()
    SetDeletedUserPersonalSiteRetentionPeriodInDays(value *int32)()
    SetExcludedFileExtensionsForSyncApp(value []string)()
    SetIdleSessionSignOut(value IdleSessionSignOutable)()
    SetImageTaggingOption(value *ImageTaggingChoice)()
    SetIsCommentingOnSitePagesEnabled(value *bool)()
    SetIsFileActivityNotificationEnabled(value *bool)()
    SetIsLegacyAuthProtocolsEnabled(value *bool)()
    SetIsLoopEnabled(value *bool)()
    SetIsMacSyncAppEnabled(value *bool)()
    SetIsRequireAcceptingUserToMatchInvitedUserEnabled(value *bool)()
    SetIsResharingByExternalUsersEnabled(value *bool)()
    SetIsSharePointMobileNotificationEnabled(value *bool)()
    SetIsSharePointNewsfeedEnabled(value *bool)()
    SetIsSiteCreationEnabled(value *bool)()
    SetIsSiteCreationUIEnabled(value *bool)()
    SetIsSitePagesCreationEnabled(value *bool)()
    SetIsSitesStorageLimitAutomatic(value *bool)()
    SetIsSyncButtonHiddenOnPersonalSite(value *bool)()
    SetIsUnmanagedSyncAppForTenantRestricted(value *bool)()
    SetPersonalSiteDefaultStorageLimitInMB(value *int64)()
    SetSharingAllowedDomainList(value []string)()
    SetSharingBlockedDomainList(value []string)()
    SetSharingCapability(value *SharingCapabilities)()
    SetSharingDomainRestrictionMode(value *SharingDomainRestrictionMode)()
    SetSiteCreationDefaultManagedPath(value *string)()
    SetSiteCreationDefaultStorageLimitInMB(value *int32)()
    SetTenantDefaultTimezone(value *string)()
}
