// Code generated by "stringer -type=modelType"; DO NOT EDIT.

package kopia

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownModel-0]
	_ = x[BackupOpModel-1]
	_ = x[RestoreOpModel-2]
	_ = x[RestorePointModel-3]
	_ = x[RestorePointDetailsModel-4]
}

const _modelType_name = "UnknownModelBackupOpModelRestoreOpModelRestorePointModelRestorePointDetailsModel"

var _modelType_index = [...]uint8{0, 12, 25, 39, 56, 80}

func (i modelType) String() string {
	if i < 0 || i >= modelType(len(_modelType_index)-1) {
		return "modelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _modelType_name[_modelType_index[i]:_modelType_index[i+1]]
}
