// Code generated by "stringer -type=ModelType"; DO NOT EDIT.

package kopia

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownModel-0]
	_ = x[BackupOpModel-1]
	_ = x[RestoreOpModel-2]
	_ = x[BackupModel-3]
	_ = x[BackupDetailsModel-4]
}

const _ModelType_name = "UnknownModelBackupOpModelRestoreOpModelBackupModelBackupDetailsModel"

var _ModelType_index = [...]uint8{0, 12, 25, 39, 50, 68}

func (i ModelType) String() string {
	if i < 0 || i >= ModelType(len(_ModelType_index)-1) {
		return "ModelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModelType_name[_ModelType_index[i]:_ModelType_index[i+1]]
}
