// Code generated by "stringer -type=OpStatus -linecomment"; DO NOT EDIT.

package operations

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[InProgress-1]
	_ = x[Completed-2]
	_ = x[Failed-3]
	_ = x[NoData-4]
}

const _OpStatus_name = "Status UnknownIn ProgressCompletedFailedNo Data"

var _OpStatus_index = [...]uint8{0, 14, 25, 34, 40, 47}

func (i OpStatus) String() string {
	if i < 0 || i >= OpStatus(len(_OpStatus_index)-1) {
		return "OpStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpStatus_name[_OpStatus_index[i]:_OpStatus_index[i+1]]
}
