// Code generated by "stringer -type=opStatus -linecomment"; DO NOT EDIT.

package operations

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[InProgress-1]
	_ = x[Successful-2]
	_ = x[Failed-3]
}

const _opStatus_name = "Status UnknownIn ProgressSuccessfulFailed"

var _opStatus_index = [...]uint8{0, 14, 25, 35, 41}

func (i opStatus) String() string {
	if i < 0 || i >= opStatus(len(_opStatus_index)-1) {
		return "opStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opStatus_name[_opStatus_index[i]:_opStatus_index[i+1]]
}
