// Code generated by "stringer -type=driveSource"; DO NOT EDIT.

package onedrive

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownDriveSource-0]
	_ = x[OneDriveSource-1]
	_ = x[SharePointSource-2]
}

const _driveSource_name = "unknownDriveSourceOneDriveSourceSharePointSource"

var _driveSource_index = [...]uint8{0, 18, 32, 48}

func (i driveSource) String() string {
	if i < 0 || i >= driveSource(len(_driveSource_index)-1) {
		return "driveSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _driveSource_name[_driveSource_index[i]:_driveSource_index[i+1]]
}
