// Code generated by "stringer -type=ServiceType -linecomment"; DO NOT EDIT.

package path

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownService-0]
	_ = x[ExchangeService-1]
	_ = x[OneDriveService-2]
	_ = x[SharePointService-3]
	_ = x[ExchangeMetadataService-4]
	_ = x[OneDriveMetadataService-5]
	_ = x[SharePointMetadataService-6]
}

const _ServiceType_name = "UnknownServiceexchangeonedrivesharepointexchangeMetadataonedriveMetadatasharepointMetadata"

var _ServiceType_index = [...]uint8{0, 14, 22, 30, 40, 56, 72, 90}

func (i ServiceType) String() string {
	if i < 0 || i >= ServiceType(len(_ServiceType_index)-1) {
		return "ServiceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceType_name[_ServiceType_index[i]:_ServiceType_index[i+1]]
}
