// Code generated by "stringer -type=Provider -linecomment"; DO NOT EDIT.

package storage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProviderUnknown-0]
	_ = x[ProviderS3-1]
	_ = x[ProviderFS-2]
}

const _Provider_name = "Unknown ProviderS3FS"

var _Provider_index = [...]uint8{0, 16, 18, 20}

func (i Provider) String() string {
	if i < 0 || i >= Provider(len(_Provider_index)-1) {
		return "Provider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Provider_name[_Provider_index[i]:_Provider_index[i+1]]
}
