// Code generated by "stringer -type=StorageProvider -linecomment"; DO NOT EDIT.

package storage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProviderUnknown-0]
	_ = x[ProviderS3-1]
}

const _StorageProvider_name = "Unknown ProviderS3"

var _StorageProvider_index = [...]uint8{0, 16, 18}

func (i StorageProvider) String() string {
	if i < 0 || i >= StorageProvider(len(_StorageProvider_index)-1) {
		return "StorageProvider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageProvider_name[_StorageProvider_index[i]:_StorageProvider_index[i+1]]
}
