// Code generated by "stringer -type=storageProvider -linecomment"; DO NOT EDIT.

package storage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProviderUnknown-0]
	_ = x[ProviderS3-1]
	_ = x[ProviderAzure-2]
}

const _storageProvider_name = "Unknown ProviderS3Azure"

var _storageProvider_index = [...]uint8{0, 16, 18, 23}

func (i storageProvider) String() string {
	if i < 0 || i >= storageProvider(len(_storageProvider_index)-1) {
		return "storageProvider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _storageProvider_name[_storageProvider_index[i]:_storageProvider_index[i+1]]
}
