name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Run-All:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Repo Code Checkout
        uses: actions/checkout@v3

      - name: Golang Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run gofmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - run: echo "Running {{ github.repository }} deployment unit tests."
      - run: go test ./...
