name: Document Generation
on:
  push:
    branches: [main]
  # remove the PR part of this once the MR creation is settled
  pull_request:
    branches: [main]

jobs:
  Generate-Markdown:
    environment: Testing
    runs-on: ubuntu-latest
    steps:

      # check out the repo
      - name: Repo Code Checkout
        uses: actions/checkout@v3
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.ref }}

      # Get values for cache paths to be used in later steps
      - id: go-cache-paths
        working-directory: ./src
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Golang Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
          cache-dependency-path: src/go.sum

      # download packages
      - name: Cache Go Mod
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Run go mod download
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./src
        run: go mod download

      # run the markdown generator
      - name: Generate Markdown
        working-directory: ./src
        run: |
          go run ./cmd/mdgen/mdgen.go generate

      # migrate generated md files into /docs/docs/cli
      - name: Move CLI .md to Docs
        run: |
          mkdir -p ./docs/docs/cli
          mv ./src/cmd/mdgen/cli_markdown/* ./docs/docs/cli/
          rm -R ./src/cmd/mdgen/cli_markdown/

      # make a new branch for the changes
      - name: Make a New Branch With the Auto-Generated Docs
        uses: EndBug/add-and-commit@v9
        with:
          add: '-A'
          new_branch: docs_autogen
          push: 'origin docs_autogen --set-upstream --force'
          message: 'Documentation Auto-generation'
          committer_name: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          default_author: github_actor

      # make a PR for the docs_autogen branch
      - name: Make a PR For the `docs_autogen` Branch
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_TIME: date -u +"%Y-%m-%dT%H:%M:%SZ"
        with:
          title: "Docs Auto-Generation"
          body: "Auto-generated Documentation update from merge to main at ${{ CURRENT_TIME }}."
          branch: "docs_autogen"
          auto-merge: squash
          update-pull-request-title-and-body: false