name: Publish Docker Container Images
on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  checkout:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

  precheck:
    needs: checkout
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check.changes }}
    steps:
      # only run CI tests if the src folder or workflow actions have changed
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
            actions:
             - '.github/**'
      - if: steps.changes.outputs.src == 'true' || steps.changes.outputs.actions == 'true'
        id: check
        run: echo "::set-output name=changes::true"

  Per-SHA-Image:
    needs: precheck
    if: needs.precheck.outputs.changes == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build
    env:
      PLATFORMS: linux/amd64,linux/arm64
    steps:

      - name: Build Corso Binaries
        run: >
          ./build.sh
          --platforms ${{ env.PLATFORMS }}

      # - name: Build Corso Binaries Locally
      #   run: >
      #     ./multiplatform-binary.sh
      #     --platforms ${{ env.PLATFORMS }}

      # apparently everyone uses this step
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # retrieve credentials for ghcr.io
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # deploy the image
      - name: Build image and push to GitHub Container Registry
        env:
          sha: git_hash=$(git rev-parse --short "$GITHUB_SHA")
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./build/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ghcr.io/alcionai/corso:${{ env.sha }}
          # use the github cache
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # check the image digest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
